### ISSUE TITLE
[bug] botbuilder -> botframework-connector (v4.4.0) fail import on jest tests

### ISSUE THREAD

**Issue by ruipiresc** [microsoft/botbuilder-js#1031]
## Versions
"node": "10"
"os": "macOS"
"jest": "^24.7.1",
"botbuilder": "4.4.0",

## Describe the bug
jest tests fail on import botbuilder

## To Reproduce
Run any test that imports botbuilder

## Expected behavior
Not faill

## Screenshots
 FAIL  src/index.test.ts
  ● Test suite failed to run

    ReferenceError: global is not defined

    > 1 | import {
        | ^
      2 |       Activity,
      3 |       ActivityTypes,
      4 |       Attachment,

      at eval (eval at Object.<anonymous> (**_node_modules/botframework-connector/src/index.ts:1:2_**), <anonymous>:3:13)
      at Object.<anonymous> (node_modules/botframework-connector/src/index.ts:1:213)
      at Object.<anonymous> (node_modules/botbuilder/src/botFrameworkAdapter.ts:10:1)
      at Object.<anonymous> (node_modules/botbuilder/src/index.ts:9:1)
      at Object.<anonymous> (src/adaptors/AdaptorAzure.ts:1:1)
      at Object.<anonymous> (src/Bot.ts:4:1)
      at Object.<anonymous> (src/index.test.ts:2:1)
[bug]

**Comment by ruipiresc** [comment]
on v4.1.7 works perfectly!

**Comment by mdrichardson** [comment]
[Fixed in 4.5](https://github.com/microsoft/botbuilder-js/commit/2af5a82753b67c0f624c4c4a76025924da24ceef). Tested to confirm.

**Comment by ruipiresc** [comment]
I confirm. It is fixed. Thank you
