### ISSUE TITLE
Can't send proactive messages using TeamsAdapter

### ISSUE THREAD

**Issue by tmuntianu** [microsoft/botbuilder-js#1041]
## Versions
SDK: 4.4.0
nodejs: v10.16.0
Using MS Teams
OS: macOS High Sierra

## Describe the bug
This bug is very similar to #714, except the solution (using `MicrosoftAppCredentials.trustServiceUrl`) doesn't work when using the TeamsAdapter from `botbuilder-teams`

If I use the regular BotFrameworkAdapter, everything works perfectly, except all of the Teams functionality that is provided by the Teams adapter.

Stacktrace:
<details>

```

[onTurnError]: Error: Authorization has been denied for this request.
index.js:44
(node:37828) UnhandledPromiseRejectionWarning: Error: Authorization has been denied for this request.
    at new RestError (/Users/tmuntianu/nodebot/node_modules/botbuilder-teams/node_modules/@azure/ms-rest-js/lib/restError.ts:18:5)
    at /Users/tmuntianu/nodebot/node_modules/botbuilder-teams/node_modules/@azure/ms-rest-js/lib/policies/deserializationPolicy.ts:117:27
    at process._tickCallback (internal/process/next_tick.js:68:7)
warning.js:18
(node:37828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
warning.js:18
(node:37828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

</details>

## To Reproduce
This is an abridged version of my Teams bot's index.js; I'm sending the restify server a request with the conversationReference and some text to send.

<details>

```javascript

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// index.js is used to setup and configure your bot

// Import required packages
const path = require('path');
const restify = require('restify');
const request = require('request');
const fs  = require('fs');
const cachedMSet = require('./metadataSet.json');

// Import required bot services. See https://aka.ms/bot-services to learn more about the different parts of a bot.
const { BotFrameworkAdapter, ConversationState, MemoryStorage, TurnContext, MessageFactory } = require('botbuilder');
const { TeamsAdapter } = require('botbuilder-teams');
const { TeamsMiddleware } = require('botbuilder-teams');
const { QuestionDialog } = require('./questionDialog');
const { MicrosoftAppCredentials } = require('botframework-connector');
// const { CardAction } = require('botbuilder-schema');
// The bot.
const { QnABot } = require('./bots/QnABot');

// Note: Ensure you have a .env file and include QnAMakerKnowledgeBaseId, QnAMakerEndpointKey and QnAMakerHost.
const ENV_FILE = path.join(__dirname, '.env');
require('dotenv').config({ path: ENV_FILE });
// Create adapter.
// See https://aka.ms/about-bot-adapter to learn more about adapters.
// const adapter = new BotFrameworkAdapter({
//     appId: process.env.MicrosoftAppId,
//     appPassword: process.env.MicrosoftAppPassword
// });
const adapter = new TeamsAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});

adapter.use(new TeamsMiddleware());
    // Create HTTP server
    let server = restify.createServer();
    // NEED TO CHANGE PORT
    server.listen(process.env.port || process.env.PORT || 8005, function() {
        console.log(`\n${ server.name } listening to ${ server.url }`);
        console.log(`\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator`);
    });
    server.use(restify.plugins.jsonBodyParser());
    server.post('/api/notify', async (req, res) => {
        let question = req.body.question;
        let answer = req.body.answer;
        let conversationReference = JSON.parse(req.body.convRef);
        await adapter.continueConversation(conversationReference, async turnContext => {
            // MicrosoftAppCredentials.trustServiceUrl(conversationReference.serviceUrl, new Date(8640000000000000));
            MicrosoftAppCredentials.trustServiceUrl(turnContext.activity.serviceUrl, new Date(8640000000000000));
            let message = MessageFactory.text('#### Question\n' + question + '\n#### Answer\n' + answer);
            message.textFormat = 'markdown';
            await turnContext.sendActivity(message);
        });
        res.send(200);
    });

```

</details>

## Expected behavior
Message is sent to user
Like in #714, this works if the user has sent a message to the bot previously, but in this case, adding the service URL to the trusted dict does nothing

I'm not sure if this issue has to do with the stated intention of [preventing spam bots](https://github.com/Microsoft/botbuilder-dotnet/issues/1301), but I'm not trying to spam the user. I want to have a delayed reply to the user who used the bot, not spam random users unaffected by the bot.

[bug]

**Comment by mdrichardson** [comment]
I'll start working on this, but my gut reaction is that this is because `botbuilder-teams` uses its own connector.

Can you verify the `botbuilder-teams` version you're using from your `package.json`? If you just run `npm i -S botbuilder-teams`, I believe it installs the one that isn't compatible with Botframework V4. Should be your issue, but want to verify.

**Comment by mdrichardson** [comment]
So, I don't like this because it's hacky, but I've got a temporary fix while I think of something better. The issue is definitely that `botbuilder-teams` uses its own `connector`. 

To fix:

1. open `node_modules/botbuilder-teams/src/teamsMiddleware.ts`
2. Add `MicrosoftAppCredentials.trustServiceUrl(serviceUrl);` right after `const serviceUrl = ...`
3. `npm i` from `node_modules/botbuilder-teams/` (this should auto-build after install. `npm run build` if not)

**Comment by tmuntianu** [comment]
Thanks! works like a charm!
I didn't realize `botbuilder-teams` uses its own connector
