### ISSUE TITLE
Add french language for the number prompt

### ISSUE THREAD

**Issue by erbizard** [microsoft/botbuilder-js#1484]
Hi,

After testing the number prompt on teams I just found an "error".
If your local is "fr" you can't use the number prompt since the language isn't imported in the prompt
`Error: E_MISSING_BUNDLE: {"locale":"fr"}
    at createError (...\node_modules\cldrjs\dist\cldr.js:339:11)
    at validate (...\node_modules\cldrjs\dist\cldr.js:355:10)
    at Cldr.main (...\node_modules\cldrjs\dist\cldr.js:669:3)
    at numberNumberingSystem (...\node_modules\globalize\dist\globalize\number.js:553:14)        
    at numberPattern (...\node_modules\globalize\dist\globalize\number.js:1433:37)
    at Globalize.numberParser.Globalize.numberParser (...\node_modules\globalize\dist\globalize\number.js:1545:13)
    at NumberPrompt.<anonymous> (...\node_modules\botbuilder-dialogs\lib\prompts\numberPrompt.js:69:51)
    at Generator.next (<anonymous>)
    at ...\node_modules\botbuilder-dialogs\lib\prompts\numberPrompt.js:7:71
    at new Promise (<anonymous>) {
  code: 'E_MISSING_BUNDLE',
  locale: 'fr'
}`

To fix that , in lib/prompts/numberPrompt.js

>[...]
const Spanish = require("cldr-data/main/es/numbers.json");
const French = require("cldr-data/main/fr/numbers.json");
const Globalize = require("globalize");
Globalize.load(Chinese, English, Dutch, German, Japanese, LikelySubtags, NumberingSystem,
Portuguese, Spanish, French);
[...]

If this can be added that will be very nice (it's sad to extend the lib for that)

regards,
Arthur Rouet.

**Comment by tracyboehrer** [comment]
@mdrichardson Can you comment on this?

**Comment by mdrichardson** [comment]
@tracyboehrer This is unrelated to the changes that I made to Confirm and Choice Prompts, as it uses the `cldr` npm package. I can look into it, however.

**Comment by mdrichardson** [comment]
@erbizard @tracyboehrer Looks like this may be a mistake as Number Prompt supports all of the same languages as Confirm/Choice prompts *except* French.

It looks like [we may be moving away from the `cldr` package](https://github.com/microsoft/botbuilder-js/issues/1440). I'll add a fix for this, but I'll need to wait until after we decide what to do with the cldr package.

**Comment by cleemullins** [comment]
I've approved the PR. Just waiting for a JS person (@christopheranderson) to chime in and merge.

**Comment by cleemullins** [comment]
PR is currently failing to build. Working with @mdrichardson to get it fixed so we can merge.

**Comment by mdrichardson** [comment]
@cleemullins Looking into it now.
