### ISSUE TITLE
todo-bot nodejs sample in the future branch doesn't show the list of todos 

### ISSUE THREAD

**Issue by sshehata-zz** [microsoft/botbuilder-js#1561]
## Versions
What package version of the SDK are you using.
This is the future branch for adaptive dialog 
https://github.com/microsoft/botbuilder-js/tree/4.future

Dependencies (package.json) - 50 todo sample
  "dependencies": {
    "@types/node": "^10.12.18",
    "botbuilder": "^4.1.6",
    "botbuilder-dialogs": "^4.1.6",
    "botbuilder-dialogs-adaptive": "^4.1.6",
    "restify": "^7.7.0"
  }

Dependencies (package.json) - main folder
    "dependencies": {
    "@azure/ms-rest-js": "^1.8.13",
    "@types/jsonwebtoken": "^8.3.2",
    "@types/lodash": "^4.14.134",
    "@typescript-eslint/eslint-plugin": "^1.10.2",
    "@typescript-eslint/parser": "^1.10.2",
    "coveralls": "^3.0.4",
    "eslint": "^5.16.0",
    "eslint-plugin-only-warn": "^1.0.1",
    "lerna": "^3.2.1",
    "mocha": "^6.1.4",
    "ms-rest-azure": "^2.6.0",
    "read-text-file": "^1.1.0",
    "replace-in-file": "^4.1.0",
    "sinon": "^7.3.2",
    "typedoc": "^0.15.0",
    "typedoc-plugin-external-module-name": "^2.1.0",
    "typedoc-plugin-markdown": "^2.2.10",
    "typescript": "^3.5.2"
  }

What nodejs version are you using
v11.10.1

What browser version are you using
Version 79.0.3945.88 (Official Build) (64-bit)

What os are you using
macOS Mojave version 10.14.6
 
## Describe the bug
Give a clear and concise description of what the bug is.
In the todo-bot nodejs sample, when trying to show the added todos, the following error appears:
(node:65368) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERROR
 Error: DialogStateManager.getValue: a scope of 'item' wasn't found.
    at DialogStateManager.getValue (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs/lib/memory/dialogStateManager.js:85:19)
    at /Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs-adaptive/lib/stringTemplate.js:91:32
    at chunks.forEach (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs-adaptive/lib/stringTemplate.js:67:42)
    at Array.forEach (<anonymous>)
    at ActivityProperty._textTemplate (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs-adaptive/lib/stringTemplate.js:67:16)
    at ActivityProperty.format (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs-adaptive/lib/activityProperty.js:68:28)
    at value.forEach (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs-adaptive/lib/actions/sendList.js:70:44)
    at Array.forEach (<anonymous>)
    at SendList.beginDialog (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs-adaptive/lib/actions/sendList.js:69:19)
    at SequenceContext.<anonymous> (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder-dialogs/lib/dialogContext.js:117:33)
    at BotFrameworkAdapter.<anonymous> (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder/lib/botFrameworkAdapter.js:638:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/sshehata/workspace/botbuilder-js-4.future-Jan-2020/libraries/botbuilder/lib/botFrameworkAdapter.js:13:65)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:65368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:65368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## To Reproduce
1. Clone repo
2. In the root folder:
* npm install
* npm run build

3. Goto the 50. todo sample and write
npm start
4. In the emulator write "add a todo named first one"
5. In the emulator write "show my todos"
6. Received the error in the cosole

## Expected behavior
It should provide a list of the added todos as shown in the previous versions

## Screenshots
![image](https://user-images.githubusercontent.com/5727188/72087664-dc61ab80-32d6-11ea-99a4-6fda9afd9c46.png)

## Additional context
This sample was working before. 

[bug]

**Comment by srinaath** [comment]
@sshehata-zz 
Thanks for the ticket. But unfortunately the https://github.com/microsoft/botbuilder-js/tree/4.future has ben culled and we do not support it now.
