### ISSUE TITLE
Intermittent 401 errors while sending typing activity

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/botbuilder-js#1814]
## Versions
NodeJS v10.16.3
BotBuilder NodeJS SDK v4.6.2
OS Ubuntu

## Describe the bug
Given below is a snippet of our code responsible for sending typing activity
```
server.post(msgEndpointPath, (req, res, next) => {
                res.send(200);
                next();
                adapter.processActivity(req, res, async (turnContext) => {
                    if (turnContext.activity.type === ActivityTypes.Message) {
                        await turnContext.sendActivity({type: ActivityTypes.Typing});
                    }
                    await bot.run(turnContext);
                });
            });
```

But our bot service's adapter's onTurnError listener is receiving directline related errors intermittently. Given below is one of the errors logged.
```
2020-02-28T04:32:42.581Z ERROR xxxxx xxxxxx 62zUdcKct3z8WXcE RfFDsO5gJSu6IVH3 root [UserId:fwAQinABNqPpUQcEmktH ConvId:3gK67i5yMrHEH9WbkaHPNP-h] Error ocurred. Error: { Error
    at new RestError (/usr/src/app/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1397:28)
    at /usr/src/app/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1849:37
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: undefined,
  statusCode: 401,
  request:
   WebResource {
     streamResponseBody: false,
     url:
      'https://directline.botframework.com/v3/conversations/3gK67i5yMrHEH9WbkaHPNP-h/activities/3gK67i5yMrHEH9WbkaHPNP-h%7C0000000',
     method: 'POST',
     headers: HttpHeaders { _headersMap: [Object] },
     body:
      '{"type":"typing","serviceUrl":"https://directline.botframework.com/","channelId":"directline","from":{"id":"xxxxxx@V2ghQot8Lko","name":"xxxxx"},"conversation":{"id":"3gK67i5yMrHEH9WbkaHPNP-h"},"recipient":{"id":"fwAQinABNqPpUQcEmktH","name":"XXXX"},"replyToId":"3gK67i5yMrHEH9WbkaHPNP-h|0000000"}',
     query: undefined,
     formData: undefined,
     withCredentials: false,
     abortSignal: undefined,
     timeout: 0,
     onUploadProgress: undefined,
     onDownloadProgress: undefined,
     operationSpec:
      { httpMethod: 'POST',
        path: 'v3/conversations/{conversationId}/activities/{activityId}',
        urlParameters: [Array],
        requestBody: [Object],
        responses: [Object],
        serializer: [Serializer] } },
  response:
   { body: '',
     headers: HttpHeaders { _headersMap: [Object] },
     status: 401 },
  body: undefined }
```
This is breaking the experience for users because onTurnError handler sends an failure message to user. So please guide us in fixing this asap.

**Comment by stevkan** [comment]
@bhushanvadgave, which version of Ubuntu are you using? And, have you been able to identify any particular action or activity taking place that is associated or happening with the type activity (i.e. an adaptive card always follows it, etc.)?

**Comment by bhushanvadgave** [comment]
@stevkan 
Our bot service runs inside docker container of OS (Debian GNU/Linux 8 jessie). Sorry I did not mention this in the issue description. Also, we do not see any pattern (like adaptive card, etc) when this error occurs.

**Comment by stevkan** [comment]
Thank you for the updated info. I'll begin trying to repro the setup and issue.

In the meantime, can you also post your code regarding the typing indicator and where it is implemented in your bot?

Thanks!

**Comment by bhushanvadgave** [comment]
@stevkan 
I have shared the code snippet responsible for posting the typing event in the issue description above. Let me know if you require anything more.

Just so you know, this error has occurred 21 times in the last 2 days (7th,8th March).

**Comment by bhushanvadgave** [comment]
@stevkan do we have any update on this?

**Comment by stevkan** [comment]
Can you try moving the send typing activity to one of the activity handlers (onMessage(), for example)? Because it's placed directly in the adapter, it is responding to everything that comes in. I suspect that there is some bit of data that _should_ be incoming, but shouldn't necessarily be something the typing activity should be acting on.

If you can try moving and test, that would be great.

**Comment by bhushanvadgave** [comment]
@stevkan The errors are still occurring even after moving typing sendActivity to onMessage handler.

**Comment by stevkan** [comment]
@bhushanvadgave, I just noticed you are sending `res.(200)` as a first action in your `server.post()`. We won't know until you test, but if this isn't the problem it may mitigate other unknown problems. When I include the `res.send(200)` in my code, I get an exception error in my Application Insights logs. The reason being is a 200 response is already sent back as part of the adapter's process. The exception comes because a 200 response was already received and, therefore, can't be set a second time. It's my suspicion that this is interfering with the typing indicator.

Try removing both the `res.send(200)` and the `next()` bits of code and test for errors.

**Comment by bhushanvadgave** [comment]
@stevkan Yes, we added `res.send(200)` and `next()` calls to fix other [issue](https://github.com/microsoft/botframework-sdk/issues/3122#issuecomment-587000378) where our bot service's `/api/message` endpoint was timing out.
I partially remember that we were facing typing activity issues even before making the above changes. But I will try reverting the changes and see if that fixes this issue.

**Comment by stevkan** [comment]
Closing due to lack of activity. If the issue persists, please feel free to re-open.
