### ISSUE TITLE
Can't Send Proactive Message After Server Restart

### ISSUE THREAD

**Issue by kevinyang372** [microsoft/botbuilder-js#1817]
## Versions
Package version: 4.7.0
NodeJs version: 13.5.1

## Describe the bug
Similar to #1041 #714 

I am trying to send proactive message to users in MSTeams. However, even after calling `MicrosoftAppCredentials.trustServiceUrl(options.serviceUrl);`, I still received the 401 `Authorization has been denied for this request.` bug. Bot starts working again after it receives a message from user.

Code:
```javascript
const params =
        {
            channelId: 'msteams',
            user: { id: options.user_id },
            conversation: {
                tenantId: options.tenantId
            },
            bot: options.bot_info,
            serviceUrl: options.serviceUrl
        }
    

MicrosoftAppCredentials.trustServiceUrl('https://smba.trafficmanager.net/jp/');
MicrosoftAppCredentials.trustServiceUrl('https://smba.trafficmanager.net/jp/v3/conversations');
MicrosoftAppCredentials.trustServiceUrl('https://smba.trafficmanager.net/');

await bot.startConversationWithUser(params);
await bot.say(options.message);
```

## To Reproduce
1. Restart Server
2. Send Message to Bill providing `user_id`, `bot_info` (bot id and name), `tenantId` and `serviceURL`
3. Authorization Error

I read the documentation about this issue [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript#avoiding-401-unauthorized-errors). Am I still missing anything when calling the trustServiceUrl?

**Comment by EricDahlvang** [comment]
Hi @kevinyang372 

The trusted serviceUrl should be the destination of the message being sent.  Have you tried:

`MicrosoftAppCredentials.trustServiceUrl(options.serviceUrl);` ?

**Comment by kevinyang372** [comment]
@EricDahlvang 

Yes! In fact `options.serviceUrl` is just `https://smba.trafficmanager.net/jp/`, which is recorded in the context of messages bot received.

**Comment by EricDahlvang** [comment]
Please share your startConversationWithUser method.

I just tried the following from a clean restart of my bot, and it is successfully sending a proactive message:

```js
    const conversationReference = {
        serviceUrl: 'https://smba.trafficmanager.net/amer/',
        activityId: '1583185080223',
        channelId: 'msteams',
        bot: {
            id: '28:zzzz-aaaa-aaaa-aaaa-zzzz', 
            name: 'Bot Health Test'
        },
        conversation: {
            id: '19:zzzzzzzzzz@thread.tacv2;messageid=1583185013082',
            isGroup: true,
            conversationType: 'channel',
            tenantId: 'zzzzz-zzzz-zzzz-zzzz-zzzzzzzzzz'
        },
        user: {
            id: '29:zzzz-zzzzz-zzzzz-zzzzzzzzzz',
            name: 'Eric Dahlvang',
            aadObjectId: 'zzzz-zzzz-zzzz-zzzz-zzzz'
        }
    };

    MicrosoftAppCredentials.trustServiceUrl(conversationReference.serviceUrl);

    await adapter.continueConversation(conversationReference, async turnContext => {
        await turnContext.sendActivity('proactive hello');
    });
```

**Comment by kevinyang372** [comment]
`startConversationWithUser` method is provided by another package botkit. You can view the source code [here](https://github.com/howdyai/botkit/blob/master/packages/botkit/src/botworker.ts#L246)

Do I have to provide `activityId` in order for it to work? Have you tried sending without it?

**Comment by EricDahlvang** [comment]
No, activityId is not required (in fact, it is cleared on outgoing messages).  I had just reconstructed a ConversationReference in code.

I apologize, I'm not familiar enough with BotKit's startConversationWithUser.  However, it does look similar, only it is not continuing a conversation.  It is creating a new one.

I've modified [16.proactive-messages](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/16.proactive-messages) to use the method copied from botkit.  This works as expected:

```js
server.get('/api/notify', async (req, res) => {
    const conversationReference = {
        serviceUrl: 'https://smba.trafficmanager.net/amer/',
        bot: {
            id: '28:zzzz-zzzz-zzzz-zzzz-zzzz',
        },
        conversation: {
            tenantId: 'zzzz-zzzz-zzzz-zzzz-zzzz'
        },
        user: {
            id: '29:zzzzz-zzzz-zz-zzz',
        }
    };

    MicrosoftAppCredentials.trustServiceUrl(conversationReference.serviceUrl);

    await startConversationWithUser(conversationReference);

    res.setHeader('Content-Type', 'text/html');
    res.writeHead(200);
    res.write('<html><body><h1>Proactive messages have been sent.</h1></body></html>');
    res.end();
});

async function startConversationWithUser(reference) {
    // this code is mostly copied from BotFrameworkAdapter.createConversation

    if (!reference.serviceUrl) { throw new Error('bot.startConversationWithUser(): missing serviceUrl.'); }

    // Create conversation
    const parameters = { bot: reference.bot, members: [reference.user], isGroup: false, activity: null, channelData: null };
    const client = adapter.createConnectorClient(reference.serviceUrl);

    // Mix in the tenant ID if specified. This is required for MS Teams.
    if (reference.conversation && reference.conversation.tenantId) {
        // Putting tenantId in channelData is a temporary solution while we wait for the Teams API to be updated
        parameters.channelData = { tenant: { id: reference.conversation.tenantId } };

        // Permanent solution is to put tenantId in parameters.tenantId
        parameters.tenantId = reference.conversation.tenantId;
    }

    const response = await client.conversations.createConversation(parameters);

    // Initialize request and copy over new conversation ID and updated serviceUrl.
    const request = TurnContext.applyConversationReference(
        { type: 'event', name: 'createConversation' },
        reference,
        true
    );

    const conversation = {
        id: response.id,
        isGroup: false,
        conversationType: null,
        tenantId: null,
        name: null
    };
    request.conversation = conversation;

    if (response.serviceUrl) { request.serviceUrl = response.serviceUrl; }

    // Create context and run middleware
    const turnContext = adapter.createContext(request);

    turnContext.sendActivity('test123 proactive');

    /*
    // create a new dialogContext so beginDialog works.
    const dialogContext = await this._controller.dialogSet.createContext(turnContext);

    this._config.context = turnContext;
    this._config.dialogContext = dialogContext;
    this._config.activity = request;
    */
}

```

**Comment by kevinyang372** [comment]
@EricDahlvang 

Sadly I am still getting the same authorization error as before. This is the code I am using:
```javascript
export async function sendMessageToUser(options: {bot: any, user_id: string, tenantId: string, bot_info: type.Msbot, serviceUrl: string, message: any}){

    const params =
        {
            channelId: 'msteams',
            user: { id: options.user_id },
            conversation: {
                tenantId: options.tenantId
            },
            bot: options.bot_info,
            serviceUrl: options.serviceUrl
        }
    
    // IMPORTANT: this is for authentication
    MicrosoftAppCredentials.trustServiceUrl(options.serviceUrl);

    // await options.bot.startConversationWithUser(params);
    // await options.bot.say(options.message);
    await startConversationWithUser(params, options.bot.controller.adapter, options.message);

}

export async function startConversationWithUser(reference: any, adapter: any, text: string) {

    if (!reference.serviceUrl) { throw new Error('bot.startConversationWithUser(): missing serviceUrl.'); }

    // Create conversation
    const parameters = { bot: reference.bot, members: [reference.user], isGroup: false, activity: null, channelData: null, tenantId: null };
    const client = adapter.createConnectorClient(reference.serviceUrl);

    // Mix in the tenant ID if specified. This is required for MS Teams.
    if (reference.conversation && reference.conversation.tenantId) {
        // Putting tenantId in channelData is a temporary solution while we wait for the Teams API to be updated
        parameters.channelData = { tenant: { id: reference.conversation.tenantId } };

        // Permanent solution is to put tenantId in parameters.tenantId
        parameters.tenantId = reference.conversation.tenantId;
    }

    const response = await client.conversations.createConversation(parameters);

    // Initialize request and copy over new conversation ID and updated serviceUrl.
    const request = TurnContext.applyConversationReference(
        { type: 'event', name: 'createConversation' },
        reference,
        true
    );

    const conversation = {
        id: response.id,
        isGroup: false,
        conversationType: null,
        tenantId: null,
        name: null
    };
    request.conversation = conversation;

    if (response.serviceUrl) { request.serviceUrl = response.serviceUrl; }

    // Create context and run middleware
    const turnContext = adapter.createContext(request);

    turnContext.sendActivity(text);
}
```

Response from server:
```
{ Error: Authorization has been denied for this request.
    at new RestError (/Users/kevin/Desktop/Github/synchro-bot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1397:28)
    at /Users/kevin/Desktop/Github/synchro-bot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1849:37
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: undefined,
  statusCode: 401,
  request:
   WebResource {
     streamResponseBody: false,
     url: 'https://smba.trafficmanager.net/jp/v3/conversations',
     method: 'POST',
     headers: HttpHeaders { _headersMap: [Object] },
     body: '{"isGroup":false,"bot":{"id":"zzzz","name":"zzz"},"members":[{"id":"zzz"}],"tenantId":"zzz","activity":null,"channelData":{"tenant":{"id":"zzz"}}}',
     query: undefined,
     formData: undefined,
     withCredentials: false,
     abortSignal: undefined,
     timeout: 0,
     onUploadProgress: undefined,
     onDownloadProgress: undefined,
     operationSpec:
      { httpMethod: 'POST',
        path: 'v3/conversations',
        requestBody: [Object],
        responses: [Object],
        serializer: [Serializer] } },
  response:
   { body: '{"message":"Authorization has been denied for this request."}',
     headers: HttpHeaders { _headersMap: [Object] },
     status: 401 },
  body: { message: 'Authorization has been denied for this request.' } }
```

**Comment by EricDahlvang** [comment]
Hey @benbrown 

Any ideas?  I'm not seeing what the problem might be here.

**Comment by benbrown** [comment]
Does it work if you call `MicrosoftAppCredentials.trustServiceUrl(conversationReference.serviceUrl);` AFTER you call startConversationWithUser?

**Comment by kevinyang372** [comment]
@benbrown 

I tried rearranging the order but it still doesn't work. Getting the same authorization error.
```javascript
const params =
        {
            channelId: 'msteams',
            user: { id: options.user_id },
            conversation: {
                tenantId: options.tenantId
            },
            bot: options.bot_info,
            serviceUrl: options.serviceUrl
        }

await options.bot.startConversationWithUser(params);
MicrosoftAppCredentials.trustServiceUrl(options.serviceUrl);
await options.bot.say(options.message);
```

**Comment by EricDahlvang** [comment]
Hey @kevinyang372 

I'm sorry, I'm not sure what to suggest since I cannot repeat the issue with the code I shared above.  

If you can share your bot project without the secrets, I'll spin it up and try to figure out what is going wrong.  (If you are not comfortable sharing the project publicly, you can find my @microsoft email address on my github profile page.)

**Comment by kevinyang372** [comment]
@EricDahlvang 
After examining the possible issues, I found out by updating all packages to the latest version fixed the problem. Thank you for supporting!

Some example code I wrote for testing could be found here:
https://github.com/kevinyang372/botbuilder-proactive-messaging
