### ISSUE TITLE
Messaging extension bot example getting 501 Error

### ISSUE THREAD

**Issue by kevinyang372** [microsoft/botbuilder-js#2287]
## Versions
botbuilder version: 4.9.0
nodejs version: 14.0.5
os: mac

## Describe the bug
I am trying to create a messaging extension action command feature with the following tutorial: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots

However, I am keep getting the following bug when invoking from Microsoft teams
```
(node:65410) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 501 ERROR
    at BotFrameworkAdapter.<anonymous> (/Users/kevin/Desktop/Github/jibee/node_modules/botbuilder/lib/botFrameworkAdapter.js:677:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kevin/Desktop/Github/jibee/node_modules/botbuilder/lib/botFrameworkAdapter.js:11:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
```

The code example I am using
`bot.js`
```javascript

import { BotFrameworkAdapter } from 'botbuilder';
import { TeamsMessagingExtensionsActionBot } from './teamsMessagingExtensionsActionBot';

const taskModuleController = new BotFrameworkAdapter({
    appId: process.env.APP_ID,
    appPassword: process.env.APP_PASSWORD
});

const bot = new TeamsMessagingExtensionsActionBot();

controller.webserver.post('/task_endpoint/', (req, res) => {
    taskModuleController.processActivity(req, res, async (context) => {
        console.log(context);
        await bot.run(context);
    });
});
```

`teamsMessagingExtensionsActionBot.js`
```javascript
const { TeamsActivityHandler, CardFactory } = require('botbuilder');

export class TeamsMessagingExtensionsActionBot extends TeamsActivityHandler {
    handleTeamsMessagingExtensionSubmitAction(context, action) {
        return {
          task: {
            type: 'continue',
            value: {
              width: 500,
              height: 450,
              title: 'Task Module Fetch Example',
              url: 'https://contoso.com/msteams/taskmodules/newcustomer',
              fallbackUrl: 'https://contoso.com/msteams/taskmodules/newcustomer'
            }
          }
        };
    }
}
```

[bug]

**Comment by mdrichardson** [comment]
@kevinyang372 The docs you linked to are for Task Modules, but you're using it in a method for Messaging Extensions. Please use [samples #50-60](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs) to guide your TeamsActivityHandler development. You can also want to review the [Messaging Extension docs](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet).

**Comment by kevinyang372** [comment]
@mdrichardson Thank you for responding! I tried the code examples in [samples #51](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/51.teams-messaging-extensions-action) but ended up getting the same error.

I set up a flag message in the bot function but apparently the call didn't even reach there:
```javascript
export class TeamsMessagingExtensionsActionBot extends TeamsActivityHandler {
    handleTeamsMessagingExtensionSubmitAction(context, action) {
      console.log('triggered');
      console.log(action.commandId);
        switch (action.commandId) {
          case 'create_survey':
              return createCardCommand(context, action);
          case 'shareMessage':
              return shareMessageCommand(context, action);
          default:
              throw new Error('NotImplemented');
          }
      }
    }
```

The activity object I got from the context of request:
```
_activity: {
    name: 'composeExtension/fetchTask',
    type: 'invoke',
    timestamp: 2020-05-29T19:56:53.523Z,
    localTimestamp: 2020-05-29T19:56:53.523Z,
    id: 'xxxx',
    channelId: 'msteams',
    serviceUrl: 'https://smba.trafficmanager.net/jp/',
    from: {
      id: 'xxxx',
      name: 'Kevin',
      aadObjectId: 'xxxx'
    },
    conversation: {
      conversationType: 'personal',
      tenantId: 'xxxx',
      id: 'xxxx'
    },
    recipient: {
      id: 'xxxx',
      name: 'testing_synchro'
    },
    entities: [ [Object] ],
    channelData: { tenant: [Object], source: [Object] },
    value: {
      commandId: 'create_survey',
      commandContext: 'compose',
      requestId: 'xxxx',
      context: [Object]
    },
    locale: 'en-US',
    rawTimestamp: '2020-05-29T19:56:53.523Z',
    rawLocalTimestamp: '2020-05-29T12:56:53.523-07:00',
    callerId: 'urn:botframework:azure'
  }
```

**Comment by mdrichardson** [comment]
@kevinyang372 Can you please include the code you have for `createCardCommand` and `shareMessageCommand`, or are you saying the samples aren't working, either? How are you installing the bot into Teams? What is your appId?

**Comment by kevinyang372** [comment]
@mdrichardson The `createCardCommand` and `shareMessageCommand` are exactly the same as the code examples in [sample #51](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/51.teams-messaging-extensions-action/bots/teamsMessagingExtensionsActionBot.js)

The appId and password shouldn't be a problem as all the other messaging functions are working properly except for the message extensions.

**Comment by mdrichardson** [comment]
I need your appId so I can look into issues on the backend. I need your install method because if you're not using the `manifest.json`, that might explain it.

**Comment by kevinyang372** [comment]
AppId: 3a9e091f-9d6a-41e6-9fd6-5689727417d9

`Manifest.json`
```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.6/MicrosoftTeams.schema.json",
    "manifestVersion": "1.6",
    "version": "1.0.1",
    "showLoadingIndicator": false,
    "id": "3a9e091f-9d6a-41e6-9fd6-5689727417d9",
    "packageName": "test_synchro",
    "developer": {
        "name": "Yunfan Yang",
        "websiteUrl": "https://1d4b5c11.ngrok.io/",
        "privacyUrl": "https://1d4b5c11.ngrok.io/private",
        "termsOfUseUrl": "https://1d4b5c11.ngrok.io/terms"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "test_synchro",
        "full": ""
    },
    "description": {
        "short": "Testing bot for synchrobotdev",
        "full": "This bot aims to test  in the microsoft teams setting"
    },
    "accentColor": "#FFFFFF",
    "bots": [
        {
            "botId": "3a9e091f-9d6a-41e6-9fd6-5689727417d9",
            "scopes": [
                "personal",
                "team",
                "groupchat"
            ],
            "supportsFiles": true,
            "isNotificationOnly": false
        }
    ],
    "composeExtensions": [
        {
            "botId": "3a9e091f-9d6a-41e6-9fd6-5689727417d9",
            "canUpdateConfiguration": true,
            "commands": [
                {
                    "id": "create_survey",
                    "type": "action",
                    "title": "create survey",
                    "description": "",
                    "initialRun": false,
                    "fetchTask": true,
                    "context": [
                        "commandBox",
                        "compose"
                    ],
                    "parameters": [
                        {
                            "name": "param",
                            "title": "param",
                            "description": ""
                        }
                    ]
                }
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": []
}
```

**Comment by kevinyang372** [comment]
Is there any update to this issue?

**Comment by mdrichardson** [comment]
I see almost no conversations on that bot in the last 6 days except for two 404 errors. 

1. Was ngrok still running?
2. Can you provide timestamps for the error?
3. How is the bot being installed in Teams?
4. Your manifest lacks the [`createCard` and `shareMessage` commands](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/51.teams-messaging-extensions-action/teamsAppManifest/manifest.json), so that may cause an issue with using the sample code in your bot.
5. That the `handleTeamsMessagingExtensionSubmitAction` isn't even being reached, it leads me to believe something is off with your code. Can you get sample 51 to work, but itself? If so, there's an issue with your code and you'll need to link me to it so I can help debug it.

**Comment by kevinyang372** [comment]
I realized there was an error in my manifest where I misdefined the dynamic parameters input to be static which caused the resource error. Thank you for all the help!
