### ISSUE TITLE
Unhandled promise rejections are deprecated.

### ISSUE THREAD

**Issue by seank-com** [Microsoft/botbuilder-js#250]
I have the following simple bot

```
var builder = require('botbuilder');
var restify = require('restify');

let server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log(`${server.name} listening to ${server.url}`);
});

server.post('/api/messages', (req, res) => {
    adapter.processActivity(req, res, async ctx => {
        console.log(`Incoming Activity of type "${ctx.activity.type}"`);
        
        if (ctx.activity.type === 'message') {
            ctx.sendActivity(ctx.activity.text);
        }
    });
});
```

When I run it, I see the following output in the console.

```
restify listening to http://[::]:3978
Incoming Activity of type "conversationUpdate"
Incoming Activity of type "conversationUpdate"
Incoming Activity of type "message"
(node:8) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'set' on a proxy that has been revoked
    at adapter.sendActivities.then (/home/bot/node_modules/botbuilder-core/lib/turnContext.js:202:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I removed my ```package-lock.json``` and my ```node_modules``` folder and reran ```npm install``` but the error persists.

**Comment by navzam** [comment]
You should return the `Promise` returned by `sendActivity()`:

```
return ctx.sendActivity(ctx.activity.text);
```

or `await` it since it looks like you're using async/await:

```
await ctx.sendActivity(ctx.activity.text);
```

Otherwise, `ctx` is revoked too early.

**Comment by seank-com** [comment]
@navzam , that was it, thank you!
