### ISSUE TITLE
unhandled undefined conditions in componentDialog

### ISSUE THREAD

**Issue by cindylarison** [microsoft/botbuilder-js#2532]
## Versions
What package version of the SDK are you using. - 4.8.0
What nodejs version are you using  - 13.11.0
What browser version are you using -  Emulator
What os are you using - Mac OS

## Describe the bug
Give a clear and concise description of what the bug is.
unchecked undefined variable causing problems in bot application

## To Reproduce
1. from a Bot mainDialog starts a secondary dialog by calling beginDialog(secondaryDialog). In this secondaryDialog the initStep throw some exception.

TypeError: Cannot read property 'status' of undefined
    at HoursWorkedDialog.<anonymous> (/Users/c/gitsrc/ext/teams-chatbot/node_modules/botbuilder-dialogs/lib/componentDialog.js:86:30)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/c/gitsrc/ext/teams-chatbot/node_modules/botbuilder-dialogs/lib/componentDialog.js:4:58) {stack: 'TypeError: Cannot read property 'status' of u…tbuilder-dialogs/lib/componentDialog.js:4:58)', message: 'Cannot read property 'status' of undefined'}

or error:

TypeError: Cannot read property 'status' of undefined
    at MyScheduleDialog.<anonymous> (/Users/c/gitsrc/ext/teams-chatbot/node_modules/botbuilder-dialogs/lib/componentDialog.js:100:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/c/gitsrc/ext/teams-chatbot/node_modules/botbuilder-dialogs/lib/componentDialog.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {stack: 'TypeError: Cannot read property 'status' of u…ctions (internal/process/task_queues.js:97:5)', message: 'Cannot read property 'status' of undefined'}

## Expected behavior
This error should not be thrown. The beginDialog should be able to handle undefined turnResult.

[bug]

**Comment by stevengum** [comment]
@johnataylor can you verify this bug and check if this is needed in the other languages as well?

**Comment by cindylarison** [comment]
it looks like the same problem exists in C# code in the following code line 66 and 109.

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs

**Comment by johnataylor** [comment]
See comments in PR. We can improve the exception text and that would be a good step, but that is as far as we would want to go. We don't want to change the behavior as we might have existing code out there potentially expecting that behavior.

FWIW agree the exception is not a great design.

**Comment by johnataylor** [comment]
@cindylarison probably the best thing to do here is handle the exception you get from your rest call locally, you can then send a message to the user of the bot indicating that functionality is temporarily not available or something like that - whatever is appropriate. You would then return a valid turn result. The alternative is to let an exception flow all the way through - this should hit the catch-all exception handler . We show the catch all error handler in the samples (it is plugged in through a subclass of the Adapter.) If you let an exception flow all the way the "turn" will not have completed and the bot's state would not have moved forward - so it should just pick up from where it was before on the next utterance.
