### ISSUE TITLE
Javascript Botframework SDK installation Failed

### ISSUE THREAD

**Issue by tusharacc** [microsoft/botbuilder-js#2776]
Package Version: 4.9
Node JS: 12.18.3
Browser: Chrome
OS: Windows 10

When I cloned the library with -

`git clone https://github.com/Microsoft/botbuilder-js.git`

It failed with below error -

> error: unable to create file libraries/botbuilder-dialogs-adaptive-testing/tests/resources/AdaptiveDialogTests/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs.AgeDialog.dialog: Filename too long

> error: unable to create file libraries/botbuilder-dialogs-adaptive-testing/tests/resources/AdaptiveDialogTests/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs.test.dialog: Filename too long

 The folder gets cloned. I am able to issue the following commands -

 
```

cd botbuilder-js

npm install

npm run build

```

However the following command fails -

`npm run test`

> 1) AdaptiveDialogTests
>        BindingOptionsAcrossAdaptiveDialogs:
>      TypeError: Cannot read property 'readText' of undefined
>       at ResourceExplorer.loadType (libraries\botbuilder-dialogs-declarative\lib\resources\resourceExplorer.js:49:277)
>       at TestRunner.<anonymous> (libraries\botbuilder-dialogs-adaptive-testing\lib\testRunner.js:7:1402)
>       at Generator.next (<anonymous>)
>       at C:\Users\T9SAU2\OneDrive - Chubb\Documents\BotService\botbuilder-js\libraries\botbuilder-dialogs-adaptive-testing\lib\testRunner.js:2:1240
>       at new Promise (<anonymous>)
>       at __awaiter (libraries\botbuilder-dialogs-adaptive-testing\lib\testRunner.js:2:335)
>       at TestRunner.runTestScript (libraries\botbuilder-dialogs-adaptive-testing\lib\testRunner.js:7:1276)
>       at Context.<anonymous> (libraries\botbuilder-dialogs-adaptive-testing\tests\adaptiveDialog.test.js:53:26)
>       at processImmediate (internal/timers.js:456:21)
>       at process.callbackTrampoline (internal/async_hooks.js:120:14)

 

Please let me know, how to resolve this issue.

**Comment by jwiley84** [comment]
File path names have a max character limit of 200 characters. 

> libraries/botbuilder-dialogs-adaptive-testing/tests/resources/AdaptiveDialogTests/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs/AdaptiveDialog_BindingOptionsAcrossAdaptiveDialogs.AgeDialog.dialog

is 200 characters. You might need to clone into a shorter base directory.

**Comment by jwiley84** [comment]
Closing due to inactivity.

**Comment by hsachinraj** [comment]
I am getting the same error. The bot is in my home folder. I am using Mac - macOS BigSur 11.2.1, NPM: 7.4.3 and node: 15.7.0

/runtime/node_modules/botbuilder-dialogs-declarative/lib/resources/resourceExplorer.js:164
            throw new Error(`Resource ${resource.id} not found.`);
                                                 ^

TypeError: Cannot read property 'id' of undefined
    at ResourceExplorer.loadType (/runtime/node_modules/botbuilder-dialogs-declarative/lib/resources/resourceExplorer.js:164:50)
    at DialogExpressionConverter.convert (/runtime/node_modules/botbuilder-dialogs-adaptive/lib/converters/dialogExpressionConverter.js:33:55)
    at /runtime/node_modules/botbuilder-dialogs-declarative/lib/defaultLoader.js:34:48
    at Array.reduce (<anonymous>)
    at DefaultLoader.load (/runtime/node_modules/botbuilder-dialogs-declarative/lib/defaultLoader.js:28:39)
    at ResourceExplorer.load (/runtime/node_modules/botbuilder-dialogs-declarative/lib/resources/resourceExplorer.js:207:23)
    at Array.<anonymous> (/runtime/node_modules/botbuilder-dialogs-declarative/lib/resources/resourceExplorer.js:178:25)
    at JSON.parse (<anonymous>)
    at ResourceExplorer.loadType (/runtime/node_modules/botbuilder-dialogs-declarative/lib/resources/resourceExplorer.js:167:29)
    at DialogExpressionConverter.convert (/runtime/node_modules/botbuilder-dialogs-adaptive/lib/converters/dialogExpressionConverter.js:33:55)

**Comment by joshgummersall** [comment]
Please try again using yarn instead of npm.
