### ISSUE TITLE
Mention a User

### ISSUE THREAD

**Issue by Genussgift** [Microsoft/botbuilder-js#317]
Tried multiples ways to mention a user with the entities array and the mentioned objects. 
Every time I get the same Error:

`BotFrameworkAdapter.processActivity(): 500 ERROR - Error: Invalid mention entity
(node:12700) UnhandledPromiseRejectionWarning: Error: Invalid mention entity
    at new RestError (C:\Users\sandras\WebstormProjects\kickerbot\node_modules\ms-rest-js\dist\lib\restError.js:18:28)
    at Conversations.<anonymous> (C:\Users\sandras\WebstormProjects\kickerbot\node_modules\botframework-connector\lib\generated\operations\conversations.js:737:33)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\sandras\WebstormProjects\kickerbot\node_modules\botframework-connector\lib\generated\operations\conversations.js:11:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:12700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

What am I doing wrong or is it a bug? How do I mention Users with v4?
I'm working with Teams.

**Comment by stevengum** [comment]
@Genussgift, if you're still encountering this problem, can you provide the code you're using for investigation?

**Comment by stevengum** [comment]
Closing due to inactivity.
