### ISSUE TITLE
Error: BotFrameworkAdapter.processActivity():500/401 ERROR

### ISSUE THREAD

**Issue by deathmood** [microsoft/botbuilder-js#3216]
## Versions
botbuilder 4.11.1
nodejs 12.14.1
mac os catalina

## Describe the bug
Each time I run a bot app (even from https://github.com/microsoft/BotBuilder-Samples) and install it into microsoft teams, I can not send messages to user.

I receive an error

```
(node:37634) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERROR
 Error: connect ETIMEDOUT 52.113.199.3:443
    at new RestError (/Users/<username>/Desktop/57.teams-conversation-bot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1403:28)
    at AxiosHttpClient.<anonymous> (/Users/<username>/Desktop/57.teams-conversation-bot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2194:35)
    at step (/Users/<username>/Desktop/57.teams-conversation-bot/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/Users/<username>/Desktop/57.teams-conversation-bot/node_modules/tslib/tslib.js:122:57)
    at rejected (/Users/<username>/Desktop/57.teams-conversation-bot/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at BotFrameworkAdapter.<anonymous> (/Users/<username>/Desktop/57.teams-conversation-bot/node_modules/botbuilder/lib/botFrameworkAdapter.js:769:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/<username>/Desktop/57.teams-conversation-bot/node_modules/botbuilder/lib/botFrameworkAdapter.js:12:65)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:37634) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```

I have recreated bot channels registration multiple times to use different app id/password - but that did not help.

## To Reproduce
1 - run a sample from botbuilder/samples repository (e.g. this one https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs/57.teams-conversation-bot)
2 - install the app into microsoft teams
3 - go to the chat with bot and try typing some commands/pressing buttons on cards

## Expected behavior
Bot sends messages/cards to me

## Screenshots
![image](https://user-images.githubusercontent.com/2758540/105616184-c8072880-5ddd-11eb-9dbc-8f5efd233113.png)
![image](https://user-images.githubusercontent.com/2758540/105616187-ca698280-5ddd-11eb-960f-4d564570d339.png)

I have not changed code of that sample.
I have same issue in my own app that I am developing right now. That app was working on Friday afternoon. But in the evening I started receiving those errors. Rolling back to previous version in git did not work

**Comment by deathmood** [comment]
sometimes I receive this type of error

```
error: {
      "type": "Error",
      "message": "BotFrameworkAdapter.processActivity(): 401 ERROR\n FetchError: request to https://login.botframework.com/v1/.well-known/keys failed, reason: connect ETIMEDOUT 52.232.26.228:443\n    at ClientRequest.<anonymous> (/Users/<username>/Documents/watermelon-msteams/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:223:5)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at TLSSocket.emit (events.js:223:5)\n    at TLSSocket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)",
      "stack":
          Error: BotFrameworkAdapter.processActivity(): 401 ERROR
           FetchError: request to https://login.botframework.com/v1/.well-known/keys failed, reason: connect ETIMEDOUT 52.232.26.228:443
              at ClientRequest.<anonymous> (/Users/<username>/Documents/watermelon-msteams/node_modules/node-fetch/lib/index.js:1461:11)
              at ClientRequest.emit (events.js:223:5)
              at ClientRequest.EventEmitter.emit (domain.js:475:20)
              at TLSSocket.socketErrorListener (_http_client.js:406:9)
              at TLSSocket.emit (events.js:223:5)
              at TLSSocket.EventEmitter.emit (domain.js:475:20)
              at emitErrorNT (internal/streams/destroy.js:92:8)
              at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
              at TeamsClient.<anonymous> (/Users/<username>/Documents/watermelon-msteams/node_modules/botbuilder/src/botFrameworkAdapter.ts:1239:23)
              at Generator.throw (<anonymous>)
              at rejected (/Users/<username>/Documents/watermelon-msteams/node_modules/botbuilder/lib/botFrameworkAdapter.js:12:65)
              at processTicksAndRejections (internal/process/task_queues.js:94:5)
    }

```

**Comment by DmitryZemlyuk** [comment]
Hi @deathmood =)
I receive similar error too. My bot workin perfect few days ago without any changes for environments.
JwtTokenExtractor.getIdentity:err! { FetchError: request to https://login.microsoftonline.com/common/discovery/v2.0/keys failed, reason: connect ETIMEDOUT 40.126.9.5:443

 I can't find resolution yet =(

**Comment by DmitryZemlyuk** [comment]
@deathmood Hi again =)
My bot working correctly now. Could you please check your issue again?

**Comment by deathmood** [comment]
@DmitryZemlyuk yes, mine too. Thanks. I guess that was some kind of maintenance on MS side. Or maybe MS does not want us to develop integrations on weekends
