### ISSUE TITLE
Nodejs process periodic restart causing "Already connected" error from app service and 502 error from frontend

### ISSUE THREAD

**Issue by bsid-scid** [microsoft/botbuilder-js#3472]
## Versions
What package version of the SDK are you using - 4.10
What nodejs version are you using - v12.18.3

## Describe the bug
We deployed a simple nodejs bot with directline app service extension to Azure app services.
The bot seems to be triggered by some unknown event that causes the node js process to restart at the **exact same time every day (UTC 07:23:39)** 
After the event the bot stops responding and requires a manual restart to resume operation.
From application insights, an "Already connected" error message is thrown by the "PayloadReceiver.connect" method.
From the frontend UI where the bot is called, an 502 error is thrown to the Chrome console.

## Expected behavior
The bot / node js process should not hang or restart periodically

## Additional context
**Bot name** 
apje13svc0002cb9bot

**Callstack as below -** 
Error:
   at PayloadReceiver.connect (at PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:29:19)at PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:29:19): D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.jsat PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:29:19): 29)
   at Server._incomingServer.createNodeServer_1.createNodeServer (at Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:66:36)at Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:66:36): D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.jsat Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:66:36): 66)
   at Server.emit (at Server.emit (events.js:182:13)at Server.emit (events.js:182:13): events.jsat Server.emit (events.js:182:13): 182)
   at Pipe.onconnection (at Pipe.onconnection (net.js:1519:8)at Pipe.onconnection (net.js:1519:8): net.jsat Pipe.onconnection (net.js:1519:8): 1519)

**Comment by stevkan** [comment]
It appears there may be a small bug related to IISNode that is causing the index.js to be re-executed when the bot has been idle after a while or after 24 hours of being active.

To try and mitigate, in the index.js file, can you replace the DL ASE specific code with the following and run, again. This is a possible fix suggested by one of the devs.

```js
if(!adapter.streamingServer || (adapter.streamingServer && !adapter.isStreamingConnectionOpen)){
    adapter.useNamedPipe(async (context) => {
        await bot.run(context);
        },
        process.env.APPSETTING_WEBSITE_SITE_NAME + '.directline'
    );
};
```

**Comment by bsid-scid** [comment]
We have tried this quick fix about two weeks ago as suggested by one of the devs / support engineers. 
Just to clarify, the issue still persists **with the above code segment added**
Is there any information regarding the bug that causes index.js to be restarted?
Also looking at the call stack, it seems like the above code segment does not entirely prevent the reconnection from happening.

**Comment by stevengum** [comment]
@bsid-scid https://github.com/microsoft/botbuilder-js/pull/3450 added logic to BotFrameworkAdapter.useNamedPipe() to prevent it from trying to connect to the NamedPipe when the adapter is already connected to said pipe.

Can you try using the latest daily drop of botbuilder via the `next` tag on npm ([`4.13.0-dev-date-20210330.sha-02423c0`](https://www.npmjs.com/package/botbuilder/v/4.13.0-dev-date-20210330.sha-02423c0)) and letting us know if that works? Thanks!

**Comment by bsid-scid** [comment]
@stevengum We've updated our botbuilder package to the latest build  (4.13.0-dev-date-20210330.sha-02423c0) as suggested on 3/30. For the past two days, we're still seeing the same "Already connected" error thrown at the exact same time (UTC 07:23:39) with the same error.

**Error:**
   at PayloadReceiver.connect (at PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:31:19)at PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:31:19): D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.jsat PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:31:19): 31)
   at Server._incomingServer.createNodeServer_1.createNodeServer (at Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:68:36)at Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:68:36): D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.jsat Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:68:36): 68)
   at Server.emit (at Server.emit (events.js:182:13)at Server.emit (events.js:182:13): events.jsat Server.emit (events.js:182:13): 182)
   at Pipe.onconnection (at Pipe.onconnection (net.js:1519:8)at Pipe.onconnection (net.js:1519:8): net.jsat Pipe.onconnection (net.js:1519:8): 1519)

**Comment by stevengum** [comment]
#3450 added a [specific error](https://github.com/microsoft/botbuilder-js/pull/3450/files#diff-bf5fa99d282e29f1911f0d79420ffcaf0dd2c8454ce852734bcbe24192d55787R1880) to be thrown when `BotFrameworkAdapter.useNamedPipe()` is called while it's already connected to a named pipe. If the adapter is already connected to the provided pipeName, `useNamedPipe()` it should finish without trying to connect to the Named Pipe. i.e. without the [`'Already connected.'`](https://github.com/microsoft/botbuilder-js/blob/6fab548c8ade620a7eb3d8905729ff6cd0649237/libraries/botframework-streaming/src/payloadTransport/payloadReceiver.ts#L37) error being thrown.

Is the BotFrameworkAdapter-thrown error showing up in your logs anywhere?

Additionally, does the application manually instantiate a `NamedPipeServer` and call its `start()` method at any time in the code? This would explain why the newly added error is not showing in the Web App's logs.

___

@bsid-scid would it be possible to share the bot's code via a secure back channel? (email, private GitHub repo, through Azure support, etc.)

**Comment by joshgummersall** [comment]
See also: https://github.com/microsoft/botbuilder-js/issues/3626

**Comment by joshgummersall** [comment]
Note: try [custom IISNode web.config settings here](https://github.com/joshgummersall/empty-bot/blob/main/web.config#L40)
