### ISSUE TITLE
TriggerTree > Test Tree test fails intermittently

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#3506]
See [this example](https://github.com/microsoft/botbuilder-js/pull/3447/checks?check_run_id=2240904262#step:10:156):

```cmd
1) TriggerTree
       Test Tree:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(found)

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (libraries/adaptive-expressions/tests/triggerTree.test.js:640:21)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:126:14)
```

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
