### ISSUE TITLE
Transcript logger middleware throwing error with botbuilder-azure-blobs library

### ISSUE THREAD

**Issue by tomSauret847** [microsoft/botbuilder-js#3684]
## Versions
What package version of the SDK are you using.
4.13.2
What nodejs version are you using
10.24.1
What os are you using
Windows 10
## Describe the bug
When switching over to the botbuilder-azure-blobs library the transcript logger middleware is throwing the below error
Error: activity.localTimezone must be defined
at Object.assertCondition (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\assertExt.js:15:15)
at condition (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:26:17)
at C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:40:13
at Object.string (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:347:5)
at Object.exports.assertActivity (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botframework-schema\lib\index.js:134:32)
at BlobsTranscriptStore. (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:204:31)
at Generator.next ()
at C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:10:71
at new Promise ()
at __awaiter (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:6:12)

## To Reproduce
1. install botbuilder-azure-blobs library
2. change the transcript logger middleware to use BlobsTranscriptStore
3. Run the bot

## Expected behavior
Transcript logger middleware log the transcripts to blob

## Additional context
I am changing over to use the botbuilder-azure-blobs library and removing the botbuilder-azure library, the logger middleware runs as expected with the old library but when you switch it will throw the above error on every turn of the conversation

**Comment by joshgummersall** [comment]
@tomSauret847, thank you for filing this issue. We use type assertions within the codebase to ensure that users 1) call methods in expected ways and 2) get useful error messages when that isn't the case. Unfortunately, this is a scenario where the type assertion is likely overly restrictive. I'll look today and see if I can make this a bit more permissive.

**Comment by joshgummersall** [comment]
I was able to reproduce the issue and verify that https://github.com/microsoft/botbuilder-js/pull/3692 fixes it.

**Comment by sgellock** [comment]
Approved - let's get this into 4.13.2

**Comment by joshgummersall** [comment]
@tomSauret847, please give version `4.13.4` a try!

**Comment by tomSauret847** [comment]
Thank you @joshgummersall I am no longer getting the error. I will push this up to our test environment for full testing.
