### ISSUE TITLE
Finalize DevEx around ValidationErrors thrown from `zod`

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#3727]
@joshgummersall, @mdrichardson in the `ConfigurationServiceClientCredentialFactory` I've updated the constructor in a first-pass at providing a better debugging experience with respect to the `ValidationErrors` thrown from `runtypes`:

```ts
    constructor(factoryOptions: ConfigurationServiceClientCredentialFactoryOptions) {
        super(null, null);
        try {
            const { MicrosoftAppId, MicrosoftAppPassword } = TypedConfig.check(factoryOptions);
            this.appId = MicrosoftAppId ?? this.appId;
            this.password = MicrosoftAppPassword ?? this.password;
        } catch (err) {
            if (isValidationErrorWithDetails(err)) {
                const e = new Error(JSON.stringify(err.details, undefined, 2));
                e.stack = err.stack;
                throw e;
            }
            throw err;
        }
    }
```

Below is an example of the newly constructed `Error` shown in cmd prompt when validation fails:

```
{
  "MicrosoftAppId": "Expected string | null, but was number",
  "MicrosoftAppPassword": "Expected string | null, but was boolean"
}
  ValidationError: Expected { MicrosoftAppId?: string | null; MicrosoftAppPassword?: string | null; }, but was incompatible
      at new ValidationError (E:\botbuilder-js\node_modules\runtypes\lib\errors.js:22:28)
      at Object.check (E:\botbuilder-js\node_modules\runtypes\lib\runtype.js:33:19)
      at new ConfigurationServiceClientCredentialFactory (lib\configurationServiceClientCredentialFactory.js:14:212)
      at createServiceClientCredentialFactoryFromConfiguration (lib\configurationServiceClientCredentialFactory.js:22:206)
      at Context.<anonymous> (tests\configurationServiceClientCredentialFactory.test.js:54:13)
      at processImmediate (internal/timers.js:461:21)
```

This is the test that causes the example error to be shown:

```js
    it('non-string values should fail', function () {
        const config = new TestConfiguration({
            MicrosoftAppId: 1,
            MicrosoftAppPassword: true,
        });
        assert.throws(
            () => createServiceClientCredentialFactoryFromConfiguration(config),
            /(?:MicrosoftAppId).*\s.*(?:MicrosoftAppPassword)/
        )
    });
```

Thoughts or suggestions?

___

@joshgummersall, I decided to lean into a discrete `Configuration`-centric helper to create the `ConfigurationBotFrameworkAuthentication` and `ConfigurationServiceClientCredentialFactory` and isolate surface area changes in advance (https://github.com/microsoft/botbuilder-js/pull/3698#discussion_r638109601):
```ts
export function createBotFrameworkAuthenticationFromConfiguration(
    configuration: Configuration,
    credentialsFactory: ServiceClientCredentialsFactory = null,
    authConfiguration: AuthenticationConfiguration = null,
    botFrameworkClientFetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>,
    connectorClientOptions: ConnectorClientOptions = {}
): BotFrameworkAuthentication
```

```ts
export function createServiceClientCredentialFactoryFromConfiguration(
    configuration: Configuration
): ConfigurationServiceClientCredentialFactory
```

_Originally posted by @stevengum in https://github.com/microsoft/botbuilder-js/issues/3698#issuecomment-852564771_

**Comment by mrivera-ms** [comment]
This has been reviewed by the SDK team. Closing as not needed.
