### ISSUE TITLE
SDK throws unhandled exception - Cannot perform 'get' on a proxy that has been revoked without additional context

### ISSUE THREAD

**Issue by orsharab** [microsoft/botbuilder-js#4058]
## Versions
package version of the SDK: 4.11.1
node.js version: v14
bot written in Typescript 4.4.4

## Describe the bug
SDK is throwing unhandled exception - "Cannot perform 'get' on a proxy that has been revoked" without additional context.
All usages of TurnContext.sendActivty are awaited.

Parsed stack - 
`[{"assembly":"at /app/node_modules/botbuilder-core/lib/botState.js:66:29","fileName":"/app/node_modules/botbuilder-core/lib/botState.js","method":"<no_method>","level":0,"line":66},{"assembly":"at processTicksAndRejections (internal/process/task_queues.js:95:5)","fileName":"internal/process/task_queues.js","method":"processTicksAndRejections","level":1,"line":95}]`

## To Reproduce
Was unable reproduce

## Expected behavior
I'd except to get more information on the exception to be able to troubleshoot the issue.

Attached the log of the unhandled exception:
[query_data (1).csv](https://github.com/microsoft/botbuilder-js/files/7895281/query_data.1.csv)

**Comment by voonsiong-lum-ihs-markit** [comment]
We are also getting this error

An unexpected error has occurred in dialogBot::_onTurnEvent: TypeError: Cannot perform 'getPrototypeOf' on a proxy that has been revoked
    at Function.[Symbol.hasInstance] (<anonymous>)
    at new DialogContext (D:\home\site\wwwroot\node_modules\botbuilder-dialogs\lib\dialogContext.js:78:25)
    at DialogSet.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder-dialogs\lib\dialogSet.js:168:20)
    at Generator.next (<anonymous>)
    at fulfilled (D:\home\site\wwwroot\node_modules\botbuilder-dialogs\lib\dialogSet.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40348) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'get' on a proxy that has been revoked
    at DialogBot.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandlerBase.js:62:29)
    at Generator.next (<anonymous>)
    at D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandlerBase.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandlerBase.js:4:12)
    at DialogBot.onTurnActivity (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandlerBase.js:61:16)
    at DialogBot.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandler.js:437:45)
    at Generator.next (<anonymous>)
    at D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandler.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandler.js:8:12)
    at D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandler.js:436:54
    at D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandler.js:948:43
    at Generator.next (<anonymous>)
    at D:\home\site\wwwroot\node_modules\botbuilder\node_modules\botbuilder-core\lib\activityHandler.js:12:71
    at new Promise (<anonymous>)

We are trying to figure out why our skill dialog bot results are not getting into the stepContext.result object.  We are looking into the context object in the CloudSkillHandler object.  We can see the skill results in the activity.value property.

We looked into the context object in the bot's async run(context) method and can see the skill results in the activity.value property.  

After the logging of the context is printed out, that's when the above-mentioned error is getting thrown.

**Comment by stevkan** [comment]
@orsharab, you say you are unable to reproduce the issue. Does this mean it occurred only once or only a few times? Do you happen to know at what point in the conversation flow that this issue presented? And, if you can tell, does it happen every time at the same point?

It's worth noting that the _usual_ culprit when this error pops up is something like `context.sendActivity()`, for example, that is lacking an `await` in front of it. I would recommend that you go thru your code and double check that everything is properly awaited.

Another culprit is attempting to set a timeout on a `sendActivity()`. Doing this will also result in the above error. Again, check your code to be sure you aren't attempting this.

**Comment by stevkan** [comment]
Closing due to lack of activity.

**Comment by orsharab** [comment]
@stevkan, It happened only once so far, we're not sure what part of the conversation it happened, we're definitely awaiting all `context.sendActivity()` calls.
The only place we're using setTimeout with `adapter.sendActivities`  is in our custom showTyping middleware due to this issue - https://github.com/microsoft/botbuilder-js/issues/2527, but it's wrapped with try catch which helped us avoiding unhandled exceptions from this middleware as oppose to botbuilder's middleware that is trying to access the context in the catch block and can cause unhandled exceptions - https://github.com/microsoft/botbuilder-js/blob/6fab548c8ade620a7eb3d8905729ff6cd0649237/libraries/botbuilder-core/src/showTypingMiddleware.ts.

Here is the custom middleware:

`import {Activity, ActivityTypes, ConversationReference, Middleware, TurnContext} from 'botbuilder';

/**
 * This class was mostly copied from bot-builder v4 SDK (ShowTypingMiddleware), the reason is that "context.adapter.sendActivities" is performed out of context (inside a setTimeout) and could cause an unhandled exception when the request is failing
 * TODO - @orel Use bot builder class once Bot Framework fixing the unhandled exception - issue https://github.com/microsoft/botbuilder-js/issues/2527
 */
export default class ShowTypingMiddleware implements Middleware {
    private readonly delay: number;
    private readonly period: number;

    /**
     * Create the SendTypingIndicator middleware
     *
     * @param delay {number} Number of milliseconds to wait before sending the first typing indicator.
     * @param period {number} Number of milliseconds to wait before sending each following indicator.
     */
    public constructor(delay = 500, period = 2000) {
        if (delay < 0) {
            throw new Error('Delay must be greater than or equal to zero');
        }

        if (period <= 0) {
            throw new Error('Repeat period must be greater than zero');
        }

        this.delay = delay;
        this.period = period;
    }

    public async onTurn(context: TurnContext, next: () => Promise<void>): Promise<void> {

        let finished = false;
        let hTimeout: any;

        /**
         * @param ctx TurnContext object representing incoming message.
         * @param delay The initial delay before sending the first indicator.
         * @param period How often to send the indicator after the first.
         */
        function startInterval(ctx: TurnContext, delay: number, period: number): void {
            hTimeout = setTimeout(
                async () => {
                    if (!finished) {
                        let typingActivity: Partial<Activity> = {
                            type: ActivityTypes.Typing,
                            relatesTo: ctx.activity.relatesTo
                        };

                        // Sending the Activity directly via the Adapter avoids other middleware and avoids setting the
                        // responded flag. However this also requires that the conversation reference details are explicitly added.
                        const conversationReference: Partial<ConversationReference> =
                            TurnContext.getConversationReference(ctx.activity);
                        typingActivity = TurnContext.applyConversationReference(typingActivity, conversationReference);

                        try {
                            await ctx.adapter.sendActivities(ctx, [typingActivity]);
                        } catch (error) { /* do nothing, this error is logged by CustomAxiosHttpClient */ }

                        // Pass in period as the delay to repeat at an interval.
                        startInterval(ctx, period, period);
                    } else {
                        // Do nothing! This turn is done and we don't want to continue sending typing indicators.
                    }
                },
                delay
            );
        }

        if (context.activity.type === ActivityTypes.Message) {
            // Set a property to track whether or not the turn is finished.
            // When it flips to true, we won't send anymore typing indicators.
            finished = false;
            startInterval(context, this.delay, this.period);
        }

        // Let the rest of the process run.
        // After everything has run, stop the indicator!
        try {
            return await next();
        }
        finally
        {
            finished = true;
            if (hTimeout) {
                clearTimeout(hTimeout);
            }
        }
    }
}
`
