### ISSUE TITLE
[IcM] Restify not working under Node.js 18

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#4367]
> Copied from [348937526](https://portal.microsofticm.com/imp/v3/incidents/details/348937526/home).

Note this is an IcM ticket, please treat it as high priority.

## Versions
What package version of the SDK are you using.
What nodejs version are you using: 18.
What browser version are you using
What os are you using

## Describe the bug

So we see below exception when migrated the node.js version to 18 even the issue is observed with sample bot  

2022-11-10T04:55:15.561817643Z     TypeError: Cannot set property closed of # which has only a getter
2022-11-10T04:55:15.561827143Z     at patch (/home/site/wwwroot/chatbot/node_modules/restify/lib/request.js:848:30)
2022-11-10T04:55:15.561830943Z     at Object. (/home/site/wwwroot/chatbot/node_modules/restify/lib/server.js:33:1)
2022-11-10T04:55:15.561834543Z     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2022-11-10T04:55:15.561837943Z     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
2022-11-10T04:55:15.561841243Z     at Module.load (node:internal/modules/cjs/loader:981:32)
2022-11-10T04:55:15.561844543Z     at Module._load (node:internal/modules/cjs/loader:827:12)
2022-11-10T04:55:15.561847943Z     at Module.require (node:internal/modules/cjs/loader:1005:19)
2022-11-10T04:55:15.561851343Z     at Module.patchedRequire [as require] (/agents/node/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
2022-11-10T04:55:15.561854743Z     at require (node:internal/modules/cjs/helpers:102:18)
2022-11-10T04:55:15.561858044Z     at Object. (/home/site/wwwroot/chatbot/node_modules/restify/lib/index.js:10:14)

## To Reproduce

1. Install Node.js 18
2. Run sample bot

## Expected behavior

The sample bot should work.

## Additional context

issue is observed with sample bot, but  

if reduce the Node.js version to 14 it works fine, but with Node 18 it does not

**Comment by anishprasad01** [comment]
Known issue in restify. Added context to IcM ticket.
