### ISSUE TITLE
`TeamsActivityHandler.onMessage` is not invoked when a file is uploaded by the user

### ISSUE THREAD

**Issue by yozachar** [microsoft/botbuilder-js#4539]
## Versions

```console
$ node --version
v18.18.0
$ npm ls   
epitoma@1.0.0 /home/us-er/Documents/workspace/gitea/epitoma
├── @microsoft/teams-ai@0.1.0-preview.2
├── @types/node@14.18.62
├── @types/restify@8.5.7
├── axios@1.5.0
├── botbuilder@4.20.1
├── env-cmd@10.1.0
├── nodemon@2.0.22
├── restify@10.0.0
├── ts-node@10.9.1
└── typescript@4.9.5
$ teamsfx -v # Weirdly `teamsfx --version` prints 1.0.0 instead.
2.0.2
$ code --version                 
1.82.2
abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
x64
$ code --profile TeamsApp --list-extensions --show-versions | grep 'teams'  
TeamsDevApp.ms-teams-vscode-extension@5.2.0
$ microsoft-edge-beta --version
Microsoft Edge 117.0.2045.31 beta
$ cat /etc/os-release                                                               
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
```

## Describe the bug

When an user upload only a file to the conversation, `onMessage` method isn't called.

## To Reproduce

1. Clone source code at https://gitea.com/yozachar/epitoma
2. Run the teams app.
3. Upload a text file.
4. [`console.log(context.activity.type)` on line 20](https://gitea.com/yozachar/epitoma/src/commit/9ad67aef7c6a98b04b11b89b147f89f5728a7e86/src/attachmentsBot.ts#L20) isn't printed.

## Expected behavior

`this.onMessage` is invoked.

## Screenshot & Console Log

![image](https://github.com/microsoft/botbuilder-js/assets/38415384/2eabf31c-4c31-45ea-915f-5ab459972bdd)

```console
[nodemon] restarting due to changes...
[nodemon] starting `node --inspect=9239 -r ts-node/register ./src/index.ts`
Debugger listening on ws://127.0.0.1:9239/45fc6b36-60ad-a8d3-4831-477852496217
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
(node:30394) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

Bot Started, restify listening to http://[::]:3978
```

---

> ### Edit:
> 
> When a message is sent
>
> ![image](https://github.com/microsoft/botbuilder-js/assets/38415384/cba6920f-6d62-4750-970c-f1aef518004f) 
>
> this happens:
>
> ```console
> Bot Started, restify listening to http://[::]:3978
> message
> 
> Received user input
> No of attachments: 1
> Asynchronous processing
>         Handling attachment of class: 'text/html' & of type: 'txt'
>         Attachment class: 'text/html' & of type: 'txt' isn't supported
> 
>         ==> Skipping unsupported attachment
> 
> AxiosError: Request failed with status code 401
> /home/us-er/Documents/workspace/gitea/epitoma/node_modules/botbuilder-core/src/turnContext.ts:556
>                     this.responded = true;
>                                   ^
> TypeError: Cannot perform 'set' on a proxy that has been revoked
>     at Proxy.<anonymous> (/home/us-er/Documents/workspace/gitea/epitoma/node_modules/botbuilder-core/src/turnContext.ts:556:35)
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/us-er/Documents/workspace/gitea/epitoma/node_modules/botbuilder-core/lib/turnContext.js:9:58)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> Waiting for the debugger to disconnect...
> ```
> 
> **_Note: Axios error is expected. Whatever happens after that. under `node_modules`, is not._**

**Comment by ramfattah** [comment]
Thanks @joe733, i'm looking into this.

**Comment by ramfattah** [comment]
Hi @joe733, 

Have you had a chance to test sample [bot-file-upload](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload) to see if you are reproducing the same issue? 

The "bot-file-upload" sample demonstrates how to upload files to Teams from a bot and how to receive a file sent to a bot as an attachment.

```js
this.onMessage(async (context, next) => {
    TurnContext.removeRecipientMention(context.activity);
    const attachments = context.activity.attachments;
    const imageRegex = /image\/.*/;
    if (attachments && attachments[0] && attachments[0].contentType === 'application/vnd.microsoft.teams.file.download.info') {
        const file = attachments[0];
        const config = {
            responseType: 'stream'
        };
        const filePath = path.join(FILES_DIR, file.name);
        await writeFile(file.content.downloadUrl, config, filePath);
        const reply = MessageFactory.text(`<b>${ file.name }</b> received and saved.`);
        reply.textFormat = 'xml';
        await context.sendActivity(reply);
    } else if (attachments && attachments[0] && imageRegex.test(attachments[0].contentType)) {
        await this.processInlineImage(context);
    } else {
        const filename = 'teams-logo.png';
        const stats = fs.statSync(path.join(FILES_DIR, filename));
        const fileSize = stats.size;
        await this.sendFileCard(context, filename, fileSize);
    }
    await next();
});
```

**Comment by joe733** [comment]
> The "bot-file-upload" sample demonstrates how to upload files to Teams from a bot and how to receive a file sent to a bot as an attachment.

My bot is attempting to simply receive an uploaded file. The steps take are very similar:

<details><summary><code>attachmentsBot.ts</code></summary>

```ts
// standard
import path from "path";
import fs from "fs";

// external
import { Attachment, TeamsActivityHandler, TurnContext } from "botbuilder";
import { MicrosoftAppCredentials } from "botframework-connector";
import axios, { AxiosError } from "axios";

// local
import { sendMessageWithIndicator } from "./common";
import config from "./config";

export class AttachmentsBot extends TeamsActivityHandler {
  constructor() {
    super();

    this.onMessage(async (context: TurnContext, next) => {
      // Determine how the bot should process the message by checking for attachments.
      console.log(context.activity.type); // ???
      if (
        context.activity.attachments &&
        context.activity.attachments.length > 0
      ) {
        console.log("\nReceived user input");
        console.log(
          `No of attachments: ${context.activity.attachments.length}`
        );
        // The user sent an attachment and the bot should handle the incoming attachment.
        await this.handleIncomingAttachment(context);
      } else {
        await context.sendActivities(
          sendMessageWithIndicator("I was expecting an attachment.")
        );
      }

      // By calling next() you ensure that the next BotHandler is run.
      await next();
    });
  }

  async handleIncomingAttachment(turnContext: TurnContext) {
    console.log("Asynchronous processing");
    // Prepare Promises to download each attachment and then execute each Promise.
    const promises = turnContext.activity.attachments.map(
      handleDifferentKindsOfAttachments
    );
    const successfulSaves = await Promise.all(promises);

    // Replies back to the user with information about
    // where the attachment is stored on the bot's server,
    // and what the name of the saved file is.
    async function replyForReceivedAttachments(
      localAttachmentData:
        | null
        | undefined
        | {
            fileName: string;
            localPath: string;
          }
    ) {
      if (localAttachmentData) {
        // Because the TurnContext was bound to this function, the bot can call
        // `TurnContext.sendActivity` via `this.sendActivity`;
        await this.sendActivities(
          sendMessageWithIndicator(
            `Attachment "${localAttachmentData.fileName}" ` +
              `has been received and saved to "${localAttachmentData.localPath}".`
          )
        );
      } else if (localAttachmentData === undefined) {
        console.log("\t==> Skipping unsupported attachment");
        await this.sendActivities(
          sendMessageWithIndicator(
            "Error: I was expecting a text file as an attachment."
          )
        );
      } else {
        await this.sendActivities(
          sendMessageWithIndicator("Error: Attachment couldn't be saved.")
        );
      }
    }

    // Prepare Promises to reply to the user with information about saved attachments.
    // The current TurnContext is bound so `replyForReceivedAttachments` can also send replies.
    const replyPromises = successfulSaves.map(
      replyForReceivedAttachments.bind(turnContext)
    );
    await Promise.all(replyPromises);
    console.log("Awaiting next user input");
  }
}

/**
 * Handle different types of attachments.
 **/
async function handleDifferentKindsOfAttachments(attachment: Attachment) {
  /**
   * NOTE:
   * This gets executed multiple times based on the number of attachments
   * Hence when only a file a uploaded the response is twice as
   * the attachment list contain two components. One the message box with
   * attachment, second the attachment itself.
   **/
  // Retrieve the attachment via the attachment's contentUrl.
  const attachmentType = attachment.content.fileType || "txt";
  console.log(
    `\tHandling attachment of class: '${attachment.contentType}' & of type: '${attachmentType}'`
  );
  if (
    attachment.contentType ===
      "application/vnd.microsoft.teams.file.download.info" &&
    attachment.contentUrl &&
    attachment.content &&
    attachment.content.fileType === "txt"
  ) {
    return downloadAttachmentAndWrite(attachment);
  }
  console.log(
    `\tAttachment class: '${attachment.contentType}' & of type: '${attachmentType}' isn't supported`
  );
  console.log();
  return undefined;
}

/**
 * Downloads attachment to the disk.
 **/
async function downloadAttachmentAndWrite(attachment: Attachment) {
  const url: string = attachment.content.downloadUrl;
  const localFileName = path.join(__dirname, "downloads", "trasnscript.txt"); // attachment.name);
  console.log(localFileName);
  const authToken = await new MicrosoftAppCredentials(
    config.botId,
    config.botPassword
  ).getToken();

  console.log(
    `\t==> Attempting to download: ${attachment.name} of class: '${
      attachment.contentType
    }' & of type: '${attachment.content.fileType || "txt"}'\n` +
      `\t==> Download Source: ${url.slice(0, 10)}...`
  );

  try {
    const response = await axios.get(url, {
      responseType: "text",
      headers: { Accept: "text/plain", Authorization: `Bearer ${authToken}` },
    });
    fs.writeFile(localFileName, response.data, (fsError) => {
      if (fsError) {
        throw fsError;
      }
    });
  } catch (error) {
    if (error instanceof AxiosError) {
      console.error(
        `\t==> Download Error: ${error.response.status} ${error.response.statusText}`
      );
    } else {
      console.error(error);
    }
    return null;
  }
  return {
    fileName: attachment.name,
    localPath: localFileName,
  };
}

```

</details>

<details><summary><code>index.ts</code></summary>

```ts
// Import required packages
import * as restify from "restify";

// Import required bot services.
// See https://aka.ms/bot-services to learn more about the different parts of a bot.
import {
  CloudAdapter,
  ConfigurationServiceClientCredentialFactory,
  ConfigurationBotFrameworkAuthentication,
  TurnContext,
} from "botbuilder";

// This bot's main dialog.
// import { AttachmentsBot } from "./teamsBot";
import { sendMessageWithIndicator } from "./common";
import { app } from "./epitomaBot";
import config from "./config";

// Create adapter.
// See https://aka.ms/about-bot-adapter to learn more about adapters.
const credentialsFactory = new ConfigurationServiceClientCredentialFactory({
  MicrosoftAppId: config.botId,
  MicrosoftAppPassword: config.botPassword,
  MicrosoftAppType: "MultiTenant",
});

const botFrameworkAuthentication = new ConfigurationBotFrameworkAuthentication(
  {},
  credentialsFactory
);

const adapter = new CloudAdapter(botFrameworkAuthentication);

// Catch-all for errors.
const onTurnErrorHandler = async (context: TurnContext, error: Error) => {
  // This check writes out errors to console log .vs. app insights.
  // NOTE: In production environment, you should consider logging this to Azure
  //       application insights.
  console.error(`\n${error}`);

  // Send a trace activity, which will be displayed in Bot Framework Emulator
  // await context.sendTraceActivity(
  //   "OnTurnError Trace",
  //   `${error}`,
  //   "https://www.botframework.com/schemas/error",
  //   "TurnError"
  // );

  // Send a message to the user
  await context.sendActivities(sendMessageWithIndicator(`${error}`));
  // await context.sendActivities(
  //   sendMessageWithIndicator(
  //     "To continue to run this bot, please fix the bot source code."
  //   )
  // );
};

// Set the onTurnError for the singleton CloudAdapter.
adapter.onTurnError = onTurnErrorHandler;

// Create the bot that will handle incoming messages.
// const app = new AttachmentsBot();

// Create HTTP server.
const server = restify.createServer();
server.use(restify.plugins.bodyParser());
server.listen(process.env.port || process.env.PORT || 3978, () => {
  console.log(`\nBot Started, ${server.name} listening to ${server.url}`);
});

// Listen for incoming requests.
server.post("/api/messages", async (req, res) => {
  await adapter.process(req, res, async (context) => {
    await app.run(context);
  });
});
```

</details>

<details><summary><code>epitomaBot.ts</code></summary>

```ts
// standard
import path from "path";

// external
// import { readFileSync } from "fs";
import { MemoryStorage, TurnContext } from "botbuilder"; // ActivityTypes
import {
  AI,
  Application,
  ConversationHistory,
  DefaultPromptManager,
  DefaultTurnState,
  OpenAIPlanner,
  OpenAIModerator,
} from "@microsoft/teams-ai";

// local
import config from "./config";
import { AttachmentsBot } from "./attachmentsBot";
import { sendMessageWithIndicator } from "./common";

/*
Planner: OpenAI planner is the main component that calls the large language model (LLM) OpenAI or Azure OpenAI. The OpenAI API is powered by a diverse set of models with different capabilities. You can also make limited customizations to our original base models for your specific use case.

Prompt manager: The prompt manager manages prompt creation. It calls functions and injects from your code into the prompt. It copies the conversation state and the user state into the prompt for you automatically.

Moderator: A moderator adds safety moderation to the input and output. It allows you to identify the user input, flag prompt injection techniques, review the output from the bot, and run it through a business logic for filtering to ensure that the bot complies with OpenAI's usage policies. You can either moderate the input or the output, or both. OpenAI moderator is the default moderator.

ref: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/how-conversation-ai-get-started#create-ai-components
*/

interface ConversationState {}
// DefaultTurnState: ConversationState, UserState, TempState
type ApplicationTurnState = DefaultTurnState<ConversationState>;

// Create AI components
const planner = new OpenAIPlanner({
  apiKey: config.openAIKey,
  defaultModel: "text-davinci-003",
  logRequests: true,
});
const moderator = new OpenAIModerator({
  apiKey: config.openAIKey,
  moderate: "both",
});
const promptManager = new DefaultPromptManager(
  path.join(__dirname, "./prompts")
);

// Define storage and application
const storage = new MemoryStorage();
export const app = new Application<ApplicationTurnState>({
  storage,
  ai: {
    planner,
    moderator,
    promptManager,
    prompt: "chat",
    history: {
      assistantHistoryType: "text",
    },
  },
});

/* ************
 *             *
 *   Actions   *
 *             *
 ************* */

// Register a handler to handle flagged input actions
app.ai.action(
  AI.FlaggedInputActionName,
  async (
    context: TurnContext,
    state: ApplicationTurnState,
    data: Record<string, any>
  ) => {
    console.log(state, data);
    await context.sendActivities(
      sendMessageWithIndicator(
        "ERR: FIA: Sorry unable to respond to your query.",
        `Your message was flagged: ${JSON.stringify(data)}`
      )
    );
    return false;
  }
);

// Register a handler to handle flagged output actions
app.ai.action(
  AI.FlaggedOutputActionName,
  async (
    context: TurnContext,
    state: ApplicationTurnState,
    data: Record<string, any>
  ) => {
    console.log(state, data);
    await context.sendActivities(
      sendMessageWithIndicator(
        "ERR: FOA: Sorry unable to respond to your query."
      )
    );
    return false;
  }
);

// Listen for user to say '/history' and then send conversation history
app.message(
  "/history",
  async (context: TurnContext, state: ApplicationTurnState) => {
    const history = ConversationHistory.toString(state, 2000, "\n\n");
    await context.sendActivities(sendMessageWithIndicator(history));
  }
);

// Listen for user to say '/reset' and then delete conversation state
app.message(
  "/reset",
  async (context: TurnContext, state: ApplicationTurnState) => {
    state.conversation.delete();
    await context.sendActivities(
      sendMessageWithIndicator(
        "Ok I've deleted the current conversation state."
      )
    );
  }
);

// Create attachments bot that will handle incoming messages
const atmBot = new AttachmentsBot();

app.ai.prompts.addFunction(
  "summarize",
  async (context: TurnContext, state: ApplicationTurnState) => {
    atmBot.run(context);
    // const transcript = readFileSync("src/downloads/transcript.txt", "utf-8");
    // console.log(transcript);
    // const _ = state;
    // return transcript;
  }
);

// // Listen for ANY message to be received.
// // MUST BE AFTER ANY OTHER MESSAGE HANDLERS
// app.activity(
//   ActivityTypes.Message,
//   async (context: TurnContext, state: ApplicationTurnState) => {
//     // Echo back users request
//     console.log(`State: ${state}`);
//     console.log(`Echo: ${context.activity.text}`);
//     await context.sendActivities(sendMessageWithIndicator("Reply from AI...?"));
//   }
// );
```

</details>

When running the `attachmentsBot` from the `epitomaBot`, `this.onMessage` does not is not called, when a file is uploaded. Ref: [`9ad67ae`](https://gitea.com/joe733/epitoma/src/commit/9ad67aef7c6a98b04b11b89b147f89f5728a7e86/src)

**Comment by ramfattah** [comment]
Hi @joe733, 

After cloning your source, I'm running into errors before testing the attachments functionality.

``` 
npm start

> epitoma@1.0.0 start
> node ./lib/src/index.js

(node:28433) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

Bot Started, restify listening to http://[::]:3978

Error: DefaultPromptManager.loadPromptTemplate(): an error occurred while loading '/Users/ram/Documents/bot/BF/js_bots/customerBots/epitoma/lib/src/prompts/chat/config.json'. The file is eithe
r invalid or missing.
```

I tried to copy the `prompts` folder manually to lib folder, now i'm running into this error only after chatting with the bot:

```
npm start

> epitoma@1.0.0 start
> node ./lib/src/index.js

(node:28626) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

Bot Started, restify listening to http://[::]:3978
message

Received user input
No of attachments: 1
Asynchronous processing
        Handling attachment of class: 'text/html' & of type: 'txt'
        Attachment class: 'text/html' & of type: 'txt' isn't supported

        ==> Skipping unsupported attachment

Error: An AI request failed because it was rate limited
/Users/ram/Documents/bot/BF/js_bots/customerBots/epitoma/node_modules/botbuilder-core/lib/turnContext.js:392
                    this.responded = true;
                                   ^

TypeError: Cannot perform 'set' on a proxy that has been revoked
    at Proxy.<anonymous> (/Users/ram/Documents/bot/BF/js_bots/customerBots/epitoma/node_modules/botbuilder-core/lib/turnContext.js:392:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ram/Documents/bot/BF/js_bots/customerBots/epitoma/node_modules/botbuilder-core/lib/turnContext.js:9:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Also, the source contains external services like OpenAI, which is not ideal for attempting to reproduce an issue. 

I will try to isolate OpenAI and other external services like teamsfx, by using the bare minimum [bot-file-upload](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload) sample which handles receiving a file sent to a bot as an attachment.

This will determine If the underlying issue is indeed with `TeamsActivityHandler.onMessage` or if it's specific to your bot.

**Comment by joe733** [comment]
> After cloning your source, I'm running into errors before testing the attachments functionality.

How did you run the program? I launched it using `F5` configured by Teams Toolkit VSCode extension.

<details><summary><code>launch.json</code></summary>

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Remote (Edge)",
      "type": "msedge",
      "request": "launch",
      "url": "https://teams.microsoft.com/l/app/${{TEAMS_APP_ID}}?installAppPackage=true&webjoin=true&${account-hint}",
      "presentation": {
        "group": "remote",
        "order": 1
      },
      "internalConsoleOptions": "neverOpen"
    },
    {
      "name": "Launch Remote (Chrome)",
      "type": "chrome",
      "request": "launch",
      "url": "https://teams.microsoft.com/l/app/${{TEAMS_APP_ID}}?installAppPackage=true&webjoin=true&${account-hint}",
      "presentation": {
        "group": "remote",
        "order": 2
      },
      "internalConsoleOptions": "neverOpen"
    },
    {
      "name": "Launch App (Edge)",
      "type": "msedge",
      "request": "launch",
      "url": "https://teams.microsoft.com/l/app/${{local:TEAMS_APP_ID}}?installAppPackage=true&webjoin=true&${account-hint}",
      "cascadeTerminateToConfigurations": ["Attach to Local Service"],
      "presentation": {
        "group": "all",
        "hidden": true
      },
      "internalConsoleOptions": "neverOpen"
    },
    {
      "name": "Launch App (Chrome)",
      "type": "chrome",
      "request": "launch",
      "url": "https://teams.microsoft.com/l/app/${{local:TEAMS_APP_ID}}?installAppPackage=true&webjoin=true&${account-hint}",
      "cascadeTerminateToConfigurations": ["Attach to Local Service"],
      "presentation": {
        "group": "all",
        "hidden": true
      },
      "internalConsoleOptions": "neverOpen"
    },
    {
      "name": "Attach to Local Service",
      "type": "node",
      "request": "attach",
      "port": 9239,
      "restart": true,
      "presentation": {
        "group": "all",
        "hidden": true
      },
      "internalConsoleOptions": "neverOpen"
    }
  ],
  "compounds": [
    {
      "name": "Debug (Edge)",
      "configurations": ["Launch App (Edge)", "Attach to Local Service"],
      "preLaunchTask": "Start Teams App Locally",
      "presentation": {
        "group": "all",
        "order": 1
      },
      "stopAll": true
    },
    {
      "name": "Debug (Chrome)",
      "configurations": ["Launch App (Chrome)", "Attach to Local Service"],
      "preLaunchTask": "Start Teams App Locally",
      "presentation": {
        "group": "all",
        "order": 2
      },
      "stopAll": true
    }
  ]
}
```

</details>


<details><summary><code>tasks.json</code></summary>

```json
// This file is automatically generated by Teams Toolkit.
// The teamsfx tasks defined in this file require Teams Toolkit version >= 5.0.0.
// See https://aka.ms/teamsfx-tasks for details on how to customize each task.
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Start Teams App Locally",
      "dependsOn": [
        "Validate prerequisites",
        "Start local tunnel",
        "Provision",
        "Deploy",
        "Start application"
      ],
      "dependsOrder": "sequence"
    },
    {
      // Check all required prerequisites.
      // See https://aka.ms/teamsfx-tasks/check-prerequisites to know the details and how to customize the args.
      "label": "Validate prerequisites",
      "type": "teamsfx",
      "command": "debug-check-prerequisites",
      "args": {
        "prerequisites": [
          "nodejs", // Validate if Node.js is installed.
          "m365Account", // Sign-in prompt for Microsoft 365 account, then validate if the account enables the sideloading permission.
          "portOccupancy" // Validate available ports to ensure those debug ones are not occupied.
        ],
        "portOccupancy": [
          3978, // app service port
          9239 // app inspector port for Node.js debugger
        ]
      }
    },
    {
      // Start the local tunnel service to forward public URL to local port and inspect traffic.
      // See https://aka.ms/teamsfx-tasks/local-tunnel for the detailed args definitions.
      "label": "Start local tunnel",
      "type": "teamsfx",
      "command": "debug-start-local-tunnel",
      "args": {
        "type": "dev-tunnel",
        "ports": [
          {
            "portNumber": 3978,
            "protocol": "http",
            "access": "public",
            "writeToEnvironmentFile": {
              "endpoint": "BOT_ENDPOINT", // output tunnel endpoint as BOT_ENDPOINT
              "domain": "BOT_DOMAIN" // output tunnel domain as BOT_DOMAIN
            }
          }
        ],
        "env": "local"
      },
      "isBackground": true,
      "problemMatcher": "$teamsfx-local-tunnel-watch"
    },
    {
      // Create the debug resources.
      // See https://aka.ms/teamsfx-tasks/provision to know the details and how to customize the args.
      "label": "Provision",
      "type": "teamsfx",
      "command": "provision",
      "args": {
        "env": "local"
      }
    },
    {
      // Build project.
      // See https://aka.ms/teamsfx-tasks/deploy to know the details and how to customize the args.
      "label": "Deploy",
      "type": "teamsfx",
      "command": "deploy",
      "args": {
        "env": "local"
      }
    },
    {
      "label": "Start application",
      "type": "shell",
      "command": "npm run dev:teamsfx",
      "isBackground": true,
      "options": {
        "cwd": "${workspaceFolder}"
      },
      "problemMatcher": {
        "pattern": [
          {
            "regexp": "^.*$",
            "file": 0,
            "location": 1,
            "message": 2
          }
        ],
        "background": {
          "activeOnStart": true,
          "beginsPattern": "[nodemon] starting",
          "endsPattern": "restify listening to|Bot/ME service listening at|[nodemon] app crashed"
        }
      }
    }
  ]
}
```

</details>

> I tried to copy the prompts folder manually to lib folder, now i'm running into this error only after chatting with the bot:

I'm on the same commit as you are and I do not see that `config.json` error, weird, and where is the `lib` folder?

```console
$ tree --gitignore
.
├── appPackage
│   ├── color.png
│   ├── manifest.json
│   └── outline.png
├── env
├── infra
│   ├── azure.bicep
│   ├── azure.parameters.json
│   └── botRegistration
│       ├── azurebot.bicep
│       └── readme.md
├── LICENSE
├── package.json
├── package-lock.json
├── README.md
├── src
│   ├── attachmentsBot.ts
│   ├── common.ts
│   ├── config.ts
│   ├── epitomaBot.ts
│   ├── index.ts
│   └── prompts
│       └── chat
│           ├── config.json
│           └── skprompt.txt
├── teamsapp.local.yml
├── teamsapp.yml
├── tsconfig.json
└── web.config

8 directories, 22 files
```

> Also, the source contains external services like OpenAI, which is not ideal for attempting to reproduce an issue.
>
> I will try to isolate OpenAI and other external services like teamsfx, by using the bare minimum [bot-file-upload](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload) sample which handles receiving a file sent to a bot as an attachment.

I understand the reproducibility part. But `teamsfx` isn't an external service.

I'm trying to create a [TeamsAI](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/how-conversation-ai-get-started) powered _bot which summarizes transcriptions uploaded as text files_. So the idea was to create an `AttachmentsBot`, which handles files uploaded by user, that gets executed when the `epitomaBot` (AIBot) attempts to read those files and reply with summary.

You can test the `AttachmentsBot` directly by commenting line `16` and uncommenting lines `14` and `62` in [`src/index.ts`](https://gitea.com/yozachar/epitoma/src/branch/main/src/index.ts).

---

**Note**

> My username on gitea was changed. Update remote
>
> ```console
> $ git remote remove origin
> $ git remote add origin https://gitea.com/yozachar/epitoma.git
> ```

> I've pushed a minor change please update your clone.

**Comment by ramfattah** [comment]
Thanks for you patience @yozachar, 

I'm also able to reproduce this issue using minimal sample [bot-file-upload](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload) from [OfficeDev/Microsoft-Teams-Samples ](https://github.com/OfficeDev/Microsoft-Teams-Samples)
repository.

Environment:
* botbuilder v4.18.0
* Channel: Teams
* node v16.20.1


```
restify listening to http://[::]:3978
/Users/ram/Documents/bot/BF/CustomerBots/js/nodejs/node_modules/botbuilder-core/lib/turnContext.js:391
                    this.responded = true;
                                   ^

TypeError: Cannot perform 'set' on a proxy that has been revoked
    at Proxy.<anonymous> (/Users/ram/Documents/bot/BF/CustomerBots/js/nodejs/node_modules/botbuilder-core/lib/turnContext.js:391:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ram/Documents/bot/BF/CustomerBots/js/nodejs/node_modules/botbuilder-core/lib/turnContext.js:9:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by ramfattah** [comment]
I couldn't reproduce the issue using the [15.handling-attachments](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/15.handling-attachments) sample in the WebChat channel; this issue might be specific to Teams.

<img src="https://github.com/microsoft/botbuilder-js/assets/38049078/563ca169-cd9b-4b8a-af69-b8146d19dc74" width="500"/>

**Comment by ramfattah** [comment]
Discussing this internally for next steps.

**Comment by ramfattah** [comment]
Thanks, @yozachar. 

Given that the issue is reproducible with the [bot-file-upload](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload) sample from the [OfficeDev/Microsoft-Teams-Samples](https://github.com/OfficeDev/Microsoft-Teams-Samples) repository, please open an issue in that repository for a more targeted resolution:
https://github.com/OfficeDev/Microsoft-Teams-Samples
