### ISSUE TITLE
500 ERROR - TypeError: Recognizers.recognizeNumber is not a function

### ISSUE THREAD

**Issue by Sastidar** [Microsoft/botbuilder-js#461]
I was following the official reservation tutorial found [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-waterfall?view=azure-bot-service-4.0&tabs=jstab) and it throws the following error. As far as I checked the function is undefined. My demo source code can be found [here](https://pastebin.com/GHN8Cg9R).

```
BotFrameworkAdapter.processActivity(): 500 ERROR - TypeError: Recognizers.recognizeNumber is not a function
(node:13844) UnhandledPromiseRejectionWarning: TypeError: Recognizers.recognizeNumber is not a function
    at Object.recognize (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-prompts\lib\numberPrompt.js:39:41)
    at NumberPrompt.onRecognize (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-dialogs\lib\prompts\numberPrompt.js:78:28)
    at NumberPrompt.dialogContinue (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-dialogs\lib\prompts\prompt.js:35:21)
    at DialogContext.continue (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-dialogs\lib\dialogContext.js:147:51)
    at adapter.processActivity (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\app.js:92:30)
    at middleware.run (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-core\lib\botAdapter.js:43:20)
    at runNext (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-core\lib\middlewareSet.js:76:44)
    at Promise.resolve.handlers.(anonymous function) (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-core\lib\middlewareSet.js:73:71)
    at read.then (D:\Development\xampp\htdocs\lab\node\cosmote-sample-bot-v4\node_modules\botbuilder-core-extensions\lib\botState.js:49:25)
    at <anonymous>
(node:13844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stevengum** [comment]
Crosslinking Microsoft/Recognizers-Text#869

**Comment by cleemullins** [comment]
Related to #420, but not a dupe. We're seeing build failure related to this now as well. 

Investigating the issues in the 1.1.0 recognizer-text.

**Comment by nyxsys** [comment]
I've tested and confirmed `numberPrompt` will work in an up to date bot using recognizers-text 1.1.2

Note: the bot in the original message is using an out of date method for initializing state storage, so it will not work for verifying the issue on your end, the documentation related to this will be updated soon.
