### ISSUE TITLE
TypeError: this.addUserAgentInfo is not a function

### ISSUE THREAD

**Issue by damadei** [Microsoft/botbuilder-js#643]
## Versions
What package version of the SDK are you using.
4.1.5
What nodejs version are you using
8.1.2
What browser version are you using
No browser
What os are you using
Win10

## Describe the bug
Give a clear and concise description of what the bug is.
When I try to run a JS Bot based on samples I'm getting this error:
[onTurnError]: TypeError: this.addUserAgentInfo is not a function
BotFrameworkAdapter.processActivity(): 500 ERROR - TypeError: this.addUserAgentInfo is not a function
botFrameworkAdapter.ts:542
(node:1188) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: TypeError: this.addUserAgentInfo is not a function
warning.js:28
(node:1188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning.js:28
index.js:92
 [onTurnError]: TypeError: this.addUserAgentInfo is not a function
BotFrameworkAdapter.processActivity(): 500 ERROR - TypeError: this.addUserAgentInfo is not a function
botFrameworkAdapter.ts:542
(node:1188) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: TypeError: this.addUserAgentInfo is not a function
warning.js:28

## To Reproduce
Clone samples repo
Run sample 4
Send any message to the bot, the error is thrown and the process exits

[bug]

**Comment by damadei** [comment]
More info, seems the error is here in botFrameworkAdapter.ts due to the function not found in ConnectorClient:

    protected createConnectorClient(serviceUrl: string): ConnectorClient {
        const client: ConnectorClient = new ConnectorClient(this.credentials, { baseUri: serviceUrl} );
        client.addUserAgentInfo(USER_AGENT);

        return client;
    }

    /**
     * Allows for mocking of the OAuth API Client in unit tests.
     * @param serviceUrl Clients service url.
     */
    protected createTokenApiClient(serviceUrl: string): TokenApiClient {
        const client = new TokenApiClient(this.credentials, { baseUri: serviceUrl} );
        client.addUserAgentInfo(USER_AGENT);
        return client;
    }

**Comment by JasonSowers** [comment]
I got this error as well here is my stack trace:

"TypeError: this.addUserAgentInfo is not a function
    at new ConnectorClientContext (c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botframework-connector\lib\connectorApi\connectorClientContext.js:29:14)
    at new ConnectorClient (c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botframework-connector\lib\connectorApi\connectorClient.js:25:9)
    at BotFrameworkAdapter.createConnectorClient (c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botbuilder\lib\botFrameworkAdapter.js:597:24)
    at BotFrameworkAdapter.<anonymous> (c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botbuilder\lib\botFrameworkAdapter.js:536:45)
    at Generator.next (<anonymous>)
    at c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botbuilder\lib\botFrameworkAdapter.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botbuilder\lib\botFrameworkAdapter.js:10:12)
    at BotFrameworkAdapter.sendActivities (c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botbuilder\lib\botFrameworkAdapter.js:515:16)
    at emit (c:\source\gitHub\BotBuilder-Samples\samples\javascript_nodejs\06.using-cards\node_modules\botbuilder-core\lib\turnContext.js:152:33)"
```

**Comment by stevengum** [comment]
I was trying to help @JasonSowers with something else when we ran across this issue, am looking into this now. 

@damadei as indicated by Jason's stack trace, the error is actually coming from further down the stack in the new [ConnectorClientContext](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-connector/src/connectorApi/connectorClientContext.ts#L37) class.

**Comment by stevengum** [comment]
@damadei, @JasonSowers, the current workaround until a new version is released is to pin your versions of ms-rest-js and ms-rest-azure-js to 1.0.455 and 1.0.176, respectively.

```bash
npm i botbuilder ms-rest-js@1.0.455 ms-rest-azure-js@1.0.176
```
