### ISSUE TITLE
I have an Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by pavigor** [Microsoft/botbuilder-js#883]
## Versions
What package version of the SDK are you using.
**botbuilder@3.16.0**
What nodejs version are you using
**v8.16.0**

## Describe the bug
Some time ago I started to get error when my bot receives the command from user:

> `Error: Hostname/IP doesn't match certificate's altnames: "Host: state.botframework.com. is not in the cert's altnames: DNS:*.azurewebsites.net, DNS:*.scm.azurewebsites.net, DNS:*.azure-mobile.net, DNS:*.scm.azure-mobile.net, DNS:*.sso.azurewebsites.net"
>     at Object.checkServerIdentity (tls.js:223:17)
>     at TLSSocket.<anonymous> (_tls_wrap.js:1122:29)
>     at emitNone (events.js:106:13)
>     at TLSSocket.emit (events.js:208:7)
>     at TLSSocket._finishInit (_tls_wrap.js:643:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
> `

## To Reproduce
The error may encounter from time to time

## Expected behavior
Not sure

[bug]

**Comment by CoHealer** [comment]
@gabog /@cleemullins, do you want a support engineer to investigate here? Chris was assigned the issue a day after the label was applied.

**Comment by EricDahlvang** [comment]
This issue needs to be moved to the v3 repository.

@pavigor what is this bot using for state?

**Comment by pavigor** [comment]
> This issue needs to be moved to the v3 repository.
> 
> @pavigor what is this bot using for state?

I am using `node-persist` as a storage for bot's subscribers.

**Comment by EricDahlvang** [comment]
I'm not sure what to make of this.  This is the first time I've seen this error.  

Is your bot behind a proxy, or using some abnormal configuration or setup?  

When was this bot first developed?  

You say you are using node-persist for state... is that a custom **IStorageClient** implementation?

Please provide the BotHandle and Microsoft App Id for the bot, so we can investigate our logs.

Some things that have changed, and could potentially be related: we have retired the default bot state service (state.botframework.com).  If your bot is using the default state service, please upgrade to one of our state service implementations: https://blog.botframework.com/2018/04/02/reminder-the-bot-framework-state-service-has-been-retired-what-you-need-to-know/

TLS 1.2 is now enforced on all Azure Service communications: https://blog.botframework.com/2018/11/06/announcement-azure-bot-service-enforcing-transport-layer-security-tls-1-2/
